### ISSUE TITLE
[Request] Module version in the README

### ISSUE THREAD

**Issue by marceloabner** [chrisk123999/chris-premades#10]
I think could be a good thing to let clear what are the latest tested versions of each module in the README, so you can make sure nothing is broken because of some update.

And I don't know if there is a way to do that, but create an alert for the player when they aren't in a "supported" version.

EDIT: Ahh, and the system version too.

**Comment by chrisk123999** [comment]
When I get a chance I'll go through and add some version numbers.  Along with a list of what automations are in the module.

**Comment by chrisk123999** [comment]
Readme has been updated with version numbers.
