### ISSUE TITLE
[Feature request] Add "Limits", "Vision 5e" and "Walled Templates" for an evolution of some spells such as Darkness.

### ISSUE THREAD

**Issue by p4535992** [chrisk123999/chris-premades#102]
Consider adding the following "Limits", "Vision 5e" and "Walled Templates" modules as mandatory and/or optional for an evolution of some spells such as Darkness.
Before I started writing some code I wanted to know if it was something you were interested in.

Here https://github.com/dev7355608/limits you can find some macro example of the new strategy used from dev7355608

**Comment by dineshm72** [comment]
I don't want to speak for him, but Chris has been fairly vocal about wanting to keep at least his implementation of Darkness as is (as in: a template on the canvas that does not enforce any actual vision limitation, and instead relies on player imagination).

If you want to use limits and vision 5e to create actual vision limitation, you may need to see if Mr Primate wants to add it to DDBI as he had done previously (and may well have already done again in v11 with the new modules, I just can't check).
