### ISSUE TITLE
[Feature request] Smite spells

### ISSUE THREAD

**Issue by stalker168** [chrisk123999/chris-premades#108]
I'm looking for an implementation of Smite spells I found these macros: https://github.com/Kuffeh1/Foundry/tree/main/Spells/Level%201
In general, they work, but there are problems: you have to use the fork Item Macro for v11.
Also, saving throw modifiers depend on attack modifiers.
It would be great to use actual versions of these spells.

**Comment by MotoMoto1234** [comment]
The DDBI bonus action smites work pretty well on their own theres no need to reinvent the wheel there.  As for the others, you can pretty much craft all the others using the same framework as DDBI's.  I believe some have been done in the midi discord over time and shared.

**Comment by stalker168** [comment]
It's sad... After 2 weeks of searching and trying to get the macros to work properly, I still did not manage to get a satisfactory result.

**Comment by MotoMoto1234** [comment]
There is more to a macro than just the script, you also need the item setup right for it.
