### ISSUE TITLE
Starry Form

### ISSUE THREAD

**Issue by stalker168** [chrisk123999/chris-premades#109]
Starry Form: Luminous Arrow (Druid Circle of Stars) uses the damage formula `@scale.circle-of-stars.starry-form[radiant] + @mod`. The result is `0[radiant]+mod` damage.
`@scale.circle-of-stars.star + @mod` formula works correctly.

Starry Form: Healing Chalice uses the damage formula `@scale.circle-of-stars.starry-form[healing] + @mod`. The result is `0[radiant]+mod` damage.
`@scale.circle-of-stars.star + @mod` formula works correctly.

Finally, Starry Form: Dragon sets the minimum value of Wisdom and Intelligence checks. But this should also work for skills that use these ability.

**Comment by chrisk123999** [comment]
Sorry for just getting around to looking at this.  As far as I can tell the scale is working correctly when the class is imported via the D&D Beyond Importer.  This module uses the scales generated from that module as a base and it appears to be working correctly that way.  I recommend taking a look at your Druid sub-class and making sure the scale is setup correctly.  The module expects the identifier to be called `starry-form`.
