### ISSUE TITLE
Sneak attack and Rakish Audacity features don't prompt for sneak attack when they should.

### ISSUE THREAD

**Issue by Asherlock** [chrisk123999/chris-premades#116]
Sneak attack does work with advantage on the roll, however it does not trigger when the user has an ally within 5ft of the target. Additionally, a swashbuckler with rakish audacity as an active effect does not get sneak attack when landing a hit on an isolated target.

Perhaps I'm missing something, but I've checked the setting and couldn't locate anything there to remedy this.

**Comment by MotoMoto1234** [comment]
Are you confirming this with advantage attribution turned on?  Its a setting in the misc tab of midiqol's workflow button.  Its a drop down setting near the top.  Turn it on, then make your attacks and confirm that you are not being confused by undetected disadvantage/advantage flags cause sneak attack can't happen if you have disadvantage and its very easy with midi to not realize you have disadvantage in specific cases.

**Comment by Asherlock** [comment]
I actually don't see that setting in MQoL > Workflow > Misc. Does it have a different name? I've gone through the MQoL docs on the repo and also can't find an advantage attribution. But I can confirm that all other advantage automation seems to work so not sure why this wouldn't.
![image](https://github.com/chrisk123999/chris-premades/assets/15909275/dd657964-7099-447c-b93c-4350f599b133)

**Comment by MotoMoto1234** [comment]
change default tooltip to advantage attribution, then you can expand the attack roll and see its flags.

**Comment by Asherlock** [comment]
That did the trick! Thank you!
