### ISSUE TITLE
Request: roll only the d6s for Hex, and display the roll results in chat

### ISSUE THREAD

**Issue by Kohinzy** [chrisk123999/chris-premades#12]
Current damage calculation for Hex ignors the damage rolled via the roll dialog, instead reroll the dice using the same function. It would better if the rolled results are kept, and only roll the d6s for Hex.

Additionally, display the roll results for Hex in chat dialogs, in order to make the calculations more clear.

**Comment by chrisk123999** [comment]
Could you screenshot the dialogue you're talking about.  If you're manually entering a damage roll it's likely you're using a module that's not supported by midi-qol.  My module uses the damage formula that is passed to me via it's workflows, so if it's not available there there isn't anything I can do.

**Comment by Kohinzy** [comment]
![image](https://user-images.githubusercontent.com/44696302/224675527-3850ed94-cde9-4e3d-ade7-3d4d38368acf.png)
![image](https://user-images.githubusercontent.com/44696302/224675724-31572f11-7c72-4cb1-a93c-06436d49b592.png)

**Comment by Kohinzy** [comment]
The roll formula is correct, but the damage of the attack is rerolled and ignored the previous roll

**Comment by chrisk123999** [comment]
Do you have any of the following modules active?
`Ready Set Roll
Better Rolls for 5e
Roll Groups
Fast Rolling by Default
Fast Rolls or Quick Rolls
Dice Tooltips
Taragnor's Gm Paranoia
WIRE(Whistler's Item Rolls Extended)
Minimal Roll Enhancements
Retroactive Advantage/Disadvantage
Max Crit
Multiattack 5e`

**Comment by Kohinzy** [comment]
no, none of these modules are active

**Comment by Kohinzy** [comment]
This is the full list of all my active modules, running on FVTT 10.291 and DnD5e 2.1.5
---------------------
About Time v;
Active-Auras v;
Active Token Effects v;
Advanced Macros v;
Advanced Spell Effects v;
Automated Animations v;
Build-a-Bonus v;
Cautious Gamemaster's Pack v;
Chris's Premades v;
Combat Carousel v;
Combat Enhancements v;
Compendium2Module v;
Compendium Folders v;
DF Curvy Walls v;
DFreds Convenient Effects v;
Dice So Nice! v;
Dice Tray v;
DND5E职业包 v;
DnD5e Drag Ruler Integration v;
Drag Ruler v;
Dynamic effects using Active Effects v;
Easy Target v;
Effect Macro v;
Enhanced Terrain Layer v;
Forien's Copy Environment v;
FXMaster v;
Health Estimate v;
Health Monitor v;
Item Macro v;
Item Piles v;
JB2A - Patreon Complete Collection v1;
lib - Color Settings v;
Library: DF Module Buttons v;
Library: Scene Packer v;
libWrapper v.0;
Maestro v;
Midi QOL v;
Monk's Active Tile Triggers v;
Monk's Little Details v;
Monk's Scene Navigation v;
Monk's TokenBar v;
Monk's Wall Enhancement v;
Multilevel Tokens v;
Nap Time (5E) v;
Narrator Tools v;
Perfect Vision v;
Plutonium v;
Polyglot v;
Quick Insert - Search Widget v;
Sequencer v;
Simple Calendar v;
Simply Portraits v;
SmallTime v;
Smart Target v;
socketlib v;
SoundFx Library v;
Speaking As v;
Stairways (Teleporter) v;
Tagger v;
Template Macro v;
Terrain Ruler v;
Tidy5e Sheet v;
Tidy UI - Game Settings v;
Times Up v;
Token Action HUD v;
Token Attacher v;
Token Info Icons v;
Token Magic FX v;
Token Mold v;
Translation: 中文 [Core] v;
Translation: 中文 [DnD5E] v;
Translation: 中文 [Mega] v;
Universal Battlemap Importer v;
User Latency v;
Wall Height v;
Warp Gate v;
Zoom/Pan Options v;

**Comment by Kohinzy** [comment]
![image](https://user-images.githubusercontent.com/44696302/224682249-c4507f15-64d2-4161-b84b-4982632a842b.png)
This is how Hex works now, in my opinion it should not roll the old formula

**Comment by chrisk123999** [comment]
Due to how midi-qol handles changing damage rolls, it's the only way.  You should never see the original roll.  Do you have Discord? It would may be easier for me to troubleshoot via DM.

**Comment by chrisk123999** [comment]
I noticed you have advanced spell effects on your list.  Is it the beta v10 version or the old v9 one?

**Comment by Kohinzy** [comment]
Discord: tetrahedron#9016

**Comment by Kohinzy** [comment]
> I noticed you have advanced spell effects on your list. Is it the beta v10 version or the old v9 one?

V9

**Comment by chrisk123999** [comment]
Issue was found, non-combined cards don't re-render the damage roll.
