### ISSUE TITLE
Hex not working

### ISSUE THREAD

**Issue by Avitale34** [chrisk123999/chris-premades#120]
Seems like hex is not applying damage when you use it

**Comment by chrisk123999** [comment]
It's very likely you have a setting wrong somewhere.  Run the troubleshooter out of the settings and post the output file here it in the Discord for further support.  Merge cards being off is a likely suspect.

**Comment by Avitale34** [comment]
[](url)
[CPR-Troubleshoot.txt](https://github.com/chrisk123999/chris-premades/files/12721677/CPR-Troubleshoot.txt)

**Comment by Avitale34** [comment]
Merge cards is on at the moment

**Comment by chrisk123999** [comment]
Nothing looks out of place in the log, could screenshot your chat card after casting hex on a target and attacking them?

**Comment by chrisk123999** [comment]
Turn off roll separate attacks, that may fix it.
