### ISSUE TITLE
[Feature Request] Add Undead Fortitude for additional monster names

### ISSUE THREAD

**Issue by T-Whiz** [chrisk123999/chris-premades#121]
Would it be possible to add Undead Fortitude to additional monster names for purposes of usability with the medkit button and DDBI munching? Attached is the list of monster names for the generic Undead Fortitude, including the few that have slightly different damage requirements. edit: revised list to split out NPCs
[Undead Fortitude.txt](https://github.com/chrisk123999/chris-premades/files/13043109/Undead.Fortitude.txt)

**Comment by MotoMoto1234** [comment]
You can change the name of the monster very briefly to "Zombie" and then hit the medkit, unless their undead fortitude is different.  In my world theres like a 5 second delay before the db changes take effect so cpr may not work right away with the medkit, give it a 5 count.  then change the name back.

**Comment by Autumn225** [comment]
In v12 this is applied manually via the generic features tab on the item medkit. It is planned to implement a way to apply this to all relevant features.
