### ISSUE TITLE
[Bug]Divine Smite not working

### ISSUE THREAD

**Issue by rinnocenti** [chrisk123999/chris-premades#122]
I can't get divine smite to work, I tried different ways but the magic selection box doesn't appear.
[CPR-Troubleshoot.txt](https://github.com/chrisk123999/chris-premades/files/12744517/CPR-Troubleshoot.txt)

**Comment by MotoMoto1234** [comment]
It prompts after everything.  If you are using confirm rolls, it prompts after the DM or someone confirms the roll.  If it still doesn't work when you follow fully through on a workflow, then I believe the checks it checks for is melee weapon attack, if you have a target, and if you have spell slots available.

**Comment by rinnocenti** [comment]
I don't use confirmation. 
![image](https://github.com/chrisk123999/chris-premades/assets/3178127/3b704291-7da5-4eb4-94d8-6a1a8b45cd57)
I have spell slots, I try others itens
![image](https://github.com/chrisk123999/chris-premades/assets/3178127/01d5f9de-6344-4aff-94fc-7644cfef9751)

![image](https://github.com/chrisk123999/chris-premades/assets/3178127/f2bfb49c-2a2c-44fb-83c7-96b002ffab7a)

I complete the attack, he even rolls a d8 from another skill, but the divine doesn't enter.

**Comment by chrisk123999** [comment]
I don't see any obvious reason in your settings as to why it would not be working.  As you're using an unsupported importer I won't be able to assist you further.
