### ISSUE TITLE
[Bug] Hex not work

### ISSUE THREAD

**Issue by rinnocenti** [chrisk123999/chris-premades#123]
[CPR-Troubleshoot.txt](https://github.com/chrisk123999/chris-premades/files/12744631/CPR-Troubleshoot.txt)
The Hex applies all effects, but does not roll the extra damage die.
It configures the disadvantages and everything, but the extra data doesn't work, it doesn't make any errors.

**Comment by chrisk123999** [comment]
I don't see any obvious setting for why it's not working for you.  As you're using an unsupported importer I won't be able to assist you further.
