### ISSUE TITLE
[Bug] BG3 Item "Piercing Shot" isn't rolled when an attack hits with a Crossbow. "Dmgspec not valid."

### ISSUE THREAD

**Issue by Janner3D** [chrisk123999/chris-premades#125]
![image](https://github.com/chrisk123999/chris-premades/assets/35965176/4e2ad260-4f7b-4b51-840d-2015315e5a03)
![image](https://github.com/chrisk123999/chris-premades/assets/35965176/1854ec3f-25f8-421e-bce6-5f24e11f8429)

Whenever I'm prompted to use a Piercing Shot after rolling to hit with a crossbow, no Piercing Shot feature is rolled. Instead, I get an error about a Dmgspec not being valid.

**Comment by chrisk123999** [comment]
Fixed in the next update.
