### ISSUE TITLE
Eldritch Blast still bugged I think

### ISSUE THREAD

**Issue by iansutherland75** [chrisk123999/chris-premades#126]
When using your premade EB is still bugged.  First casting seems to fire off just fine, but if you cast again the damage roll doesn't happen until the script times out?  It takes up to 5 minutes some times.

**Comment by iansutherland75** [comment]
midi-qol | called macro error in Eldritch Blast Actor.h3OjgrYi1toVgehg.Item.1G1CFJEWZuplTZAh macro function.chrisPremades.macros.eldritchBlast.damage TypeError: Cannot read properties of undefined (reading '_formula')
    at Workflow.damage (eldritchBlast.js:35:45)
    at async Proxy.eval (eval at callMacro (workflow.js:1926:17), <anonymous>:3:8)
    at async Promise.allSettled (index 0)
    at async Workflow.callMacros (workflow.js:1806:17)
    at async Workflow._next (workflow.js:679:6)
    at async Workflow.next (workflow.js:312:11)
    at async Workflow.next (workflow.js:312:11)
    at async Workflow.next (workflow.js:312:11)
    at async Item5e.doAttackRoll (itemhandling.js:592:3)
    at async Workflow._next (workflow.js:507:6)
    at async Workflow.next (workflow.js:312:11)
    at async Workflow.next (workflow.js:312:11)
    at async Workflow.next (workflow.js:312:11)
    at async Workflow.next (workflow.js:312:11)
    at async Workflow.next (workflow.js:312:11)

**Comment by chrisk123999** [comment]
Could you run the troubleshooter and put the file it outputs here?

**Comment by iansutherland75** [comment]
/////////////// Game Information ///////////////
Foundry: 11.311
System: 2.3.1
Chris's Premades: 0.7.28

/////////////// Required Modules ///////////////
Automated Animations: 4.2.67
Build A Bonus: 11.3.0
Dynamic Active Effects: 11.0.18
DFreds Convenient Effects: 6.0.0
Effect Macro: 11.0.1
libWrapper: 1.12.13.0
Midi-Qol: 11.0.22
Sequencer: 3.1.4
Socketlib: 1.0.13
Template Macro: 11.0.0
Token Attacher: v4.5.13
Warpgate: 1.18.3

/////////////// Optional Modules ///////////////
Advanced Token Effects: 0.7.0
About Time: Missing!
Custom Character Sheet Sections: Missing!
Compendium Folders: Missing!
D&D Beyond Importer: 3.4.73
Simple Calendar: 2.4.3
FXMaster: 4.0.2
Item Macro: 1.9.0+1
Jules&Ben's Animated Assets (F): 0.6.1
Jules&Ben's Animated Assets (P): 0.6.1
Quick Insert: Missing!
Small Time: Missing!
Tidy 5e Sheet: Missing!
Times Up: 11.0.3
Visual Active Effects: Missing!
undefined: Missing!

/////////////// Incompatible Modules ///////////////

/////////////// CPR Settings ///////////////
Automation Verification: true
Breaking Version Change: 7
Show Names: true
Priority Queue: true
Item Replacer Access: false
Item Configuration Access: false
Movement Listener: true
Template Listener: true
Keep Summon Actors Updated: false
Minions use caster's initiative: false
Player choses creatures for conjure spells: false
Effect Auras: true
Active Effect Additions: true
Active Effect Origin Fix: true
Skill Patching: true
Save Patching: true
Automatic VAE Descriptions: true
No NPC VAE Descriptions: false
VAE Temporary Item Buttons: true
Blinded and Invisibility Changes: true
LastGM: XxIYNTgyPNE6RBjo
Combat Listener: true
Short / Long Rest Listener: true
Movement Triggers: [object Object]
Use Additional Compendiums: true
Additional Compendiums: midi-srd.Midi SRD Feats, midi-srd.Midi SRD Spells, midi-srd.Midi SRD Items, midi-qol.midiqol-sample-items
Personal Item Compendium: world.ddb-curse-of-strahd-ddb-items
Personal Spell Compendium: world.ddb-curse-of-strahd-ddb-spells
Personal Monster Compendium: world.ddb-curse-of-strahd-ddb-monsters
Personal Racial Trait Compendium: world.ddb-curse-of-strahd-ddb-racial-traits
Condition Resistance Mechanic: true
Condition Vulnerability Mechanic: true
On Hit Automation: true
Armor of Agathys Automation: true
Beacon of Hope Automation: true
Darkness Spell Automation: true
Fog Cloud Spell Automation: true
Death Ward Automation: true
Elemental Adept Automation: true
Mirror Image Automation: true
Protection from Evil and Good Automation: true
Sanctuary Automation: true
Ranged Divine Smite: false
Unarmed Strike Divine Smite: false
DMG Cleave Mechanic: true
Shifter Wildhunt Automation: true
Undead Fortitude Automation: false
Exploding Heals: false
Shield Guardian Automation: true
Warding Bond Automation: true
Attack Listener: true
Magic Missile Toggle: false
Strength of the Grave Automation: false
Relentless Endurance Automation: false
Shadow of Moil Spell Automation: true
Emboldening Bond: false
Manual Rolls: false
Ignore GM Rolls: true
Randomizer: false
Humanoid Randomizer Settings: [object Object]
Dice So Nice Compatability: true
Arcane Ward Automation: false
Other Summons Folder: Chris Premades
Item Features: true
Baldur's Gate 3 Weapon Actions: false

/////////////// Item Macro Settings ///////////////
Character Sheet Hook: false

/////////////// Midi-Qol Settings ///////////////
Roll Automation Support: true
Apply Convenient Effects: CE > Items
Roll Seperate Attack Per Target: false
Merge Card: true

/////////////// Warpgate User Permissions ///////////////
Create Tokens: true
Configure Tokens: true
Browse Files: true

**Comment by chrisk123999** [comment]
Could you screenshot your eldritch blast details tab?

**Comment by iansutherland75** [comment]
![image](https://github.com/chrisk123999/chris-premades/assets/5667167/c92cca23-d027-449d-ac91-d44482b6cb03)
