### ISSUE TITLE
[Request] Consider using a bundler to improve performance in network environment

### ISSUE THREAD

**Issue by rikmarais** [chrisk123999/chris-premades#133]
This module does a very large number of ES6 module imports eg.
```js
import {queue} from '../../../../utility/queue.js';
```
On a network environment, this can lead to a substantial performance impact during the module loading and init steps.

On The Forge, we've encountered cases where imports start to fail and/or be unable to cache the JS files properly once a threshold number of them are started on machines running macOS and Chrome. Firefox seems to handle it properly on macOS, but Chrome fails consistently if the number of imports are above the threshold, which seems to vary based on factors like connection speed. 

The issue appears to relate to the way the browser caches the JS files, and browsers can have trouble caching effectively when imports lead to a large number of files, as is the case in this module.

This module was in play in most of the cases we encountered, and we wanted to reach out to ask if it could be possible to include a bundling step when packaging the module for release. The bundler combines multiple JavaScript files into one (or a few) output file(s) for more efficient delivery and execution, reducing the number of imports. This can streamline the performance of the module and prevent potential import-related performance issues.

If you think this issue could be picked up, there are some good options for bundling modules. [Vite](https://foundryvtt.wiki/en/development/guides/vite) is popular for FoundryVTT but alternatives such as WebPack, Gulp, Browserify, and others also exist.

**Comment by chrisk123999** [comment]
I've not had anyone report this issue with me.  Feel free to make a PR however.

**Comment by rikmarais** [comment]
> I've not had anyone report this issue with me. Feel free to make a PR however.

Understandable, though I think that's because they assume it's a problem in our infrastructure rather than with macOS/Chrome having trouble caching JS imports under certain conditions.

Could I please ask you to reopen the issue so that I can link to it in a PR which introduces bundling?
