### ISSUE TITLE
Protection from Evil and Good type matching is too simplistic

### ISSUE THREAD

**Issue by SirGarhi** [chrisk123999/chris-premades#139]
Protection from Evil and Good only looks for racial types that exactly match one in the following list ['aberration', 'celestial', 'elemental', 'fey', 'fiend', 'undead']

This misses a whole bunch of monsters that it should apply to, including several found in the SRD such as Barbed Devils which are typed as "Fiend (Devil)"

**Comment by chrisk123999** [comment]
I can likely change it to look for a partial match.

**Comment by SirGarhi** [comment]
Apologies, something else must be interfering in the world I was just playing in. Testing on my local server PfEG is working flawlessly with a Barbed Devil pulled out of the SRD compendium. "Fiend (Devil)" on the character sheet is still matched to just "fiend" internally.

**Comment by MotoMoto1234** [comment]
The other server probably had `Fiend (Devil)` in the custom field, I've seen really bad importer modules do this.
