### ISSUE TITLE
Red Error

### ISSUE THREAD

**Issue by dallasrt** [chrisk123999/chris-premades#142]
![image](https://github.com/chrisk123999/chris-premades/assets/79125274/32a34056-f8ff-4b44-bf6a-8cd88b159c7b)
 Do not know if this is an issue, but thought I would post here.

**Comment by chrisk123999** [comment]
Does this happen every time you load in?  Do you have a token without an actor on the scene?

**Comment by MotoMoto1234** [comment]
I think this also happens when theres no active scene?

**Comment by dallasrt** [comment]
I have an active scene and all tokens are accounted for.
