### ISSUE TITLE
Problem with Hunter's Mark

### ISSUE THREAD

**Issue by stalker168** [chrisk123999/chris-premades#148]
When using the Hunter's Mark spell on the target, the desired effect is created, but the source has problems with Warpgate:

- A duplicate CPR Warpgate mutation was detected and removed!
- Warp Gate | WARNING | Duplication mutation name detected, "Hunter's Mark". Stopping mutation.

![image](https://github.com/chrisk123999/chris-premades/assets/31571343/8cf1d1d7-f6c9-42e6-9698-08e74bff57bc)

Foundry - v11 305
DnD5e - 2.3.1
All modules have been updated

**Comment by MotoMoto1234** [comment]
They can't be updated because dae requires v11.309, I suspect your midi is misbehaving and yelling at you to update dae.  But then you can't cause dae requires 309.  You can fix this issue by hitting revert, but you need to backup and update foundry.

**Comment by stalker168** [comment]
> They can't be updated because dae requires v11.309, I suspect your midi is misbehaving and yelling at you to update dae. But then you can't cause dae requires 309. You can fix this issue by hitting revert, but you need to backup and update foundry.

I updated Foundry to 11.309.
Build a Bonus has also been updated to 11.4.2 Everything else is relevant (at least for this version of Foundry).
But this did not help in solving the Hunter's Mark problem.

**Comment by MotoMoto1234** [comment]
Its a notorious problem users have with hunters mark.  You guys try to recast it to move it instead of use the temp feature to move it and you get the duplicate mutation issue.  If you want to move it use the move temp item.  If you want to undo it, either end the effect on the ranger or hit the revert on the top bar of the actor.

**Comment by stalker168** [comment]
> Its a notorious problem users have with hunters mark. You guys try to recast it to move it instead of use the temp feature to move it and you get the duplicate mutation issue. If you want to move it use the move temp item. If you want to undo it, either end the effect on the ranger or hit the revert on the top bar of the actor.

But the problem arises when creating the effect for the first time.
An effect is created on the target. But when creating an effect on the source, an error occurs.

**Comment by MotoMoto1234** [comment]
and that error is because the prior hunter's mark is already on them still, it needs to be removed by hitting revert on the top bar of the ranger.

**Comment by MotoMoto1234** [comment]
If this doesn't resolve it you should join CPR's discord so you can get quicker and more efficient help.

**Comment by stalker168** [comment]
> and that error is because the prior hunter's mark is already on them still, it needs to be removed by hitting revert on the top bar of the ranger.

Yes, it helped. Thank you very much!
The solution was rather unobvious for me.
