### ISSUE TITLE
Animation Null Error

### ISSUE THREAD

**Issue by Dyrnwyrm** [chrisk123999/chris-premades#151]
I tried everything, the issue still persist, maybe is a console fake error?
It started before the update, seems like is a "common" issue in a few modules but i cant really find an answer on this problem.

![image](https://github.com/chrisk123999/chris-premades/assets/129613553/1544ef38-f675-4378-a149-f7aa5cf4a366)

**Comment by Dyrnwyrm** [comment]
Issue fixed on active auras, is related to a player token updating its X Y position on the canvas while the GM is not looking that scene, using routing lib recommended configuration fixes the issue on Rideable.

**Comment by Dyrnwyrm** [comment]
This still pops up when a player moves on a scene thats not being look at by the GM, nothing game breaking just annoying

![image](https://github.com/chrisk123999/chris-premades/assets/129613553/8d067d8f-f25c-4eed-9dae-83c9b57c0d23)

**Comment by chrisk123999** [comment]
Fixed in the next release.
