### ISSUE TITLE
Apply all Chris's Premades Issue

### ISSUE THREAD

**Issue by Aiacos** [chrisk123999/chris-premades#155]
Hi,
Apply all Chris's Premades Automations cause some spell to break with errors in attachments
Thanks,
L.
![enable](https://github.com/chrisk123999/chris-premades/assets/1658617/0052a03f-18d1-4622-aeac-a54c617ced12)
![Issue](https://github.com/chrisk123999/chris-premades/assets/1658617/475cf8b1-a6f1-47dd-b17b-91d43bc1ce57)

**Comment by MotoMoto1234** [comment]
You possibly are already concentrating on hunters mark and tried to recast it.  I'd join his discord as its easier to troubleshoot this there.  https://discord.gg/7gn8DAewrZ
