### ISSUE TITLE
[SUGGESTION] Consider adding support for Wall spells

### ISSUE THREAD

**Issue by Ikabodo** [chrisk123999/chris-premades#16]
The wall spells (Wall of Force, Wind Wall, Wall of Fire and Wall of Water) are kinda hard to manage in foundry. Maybe something that can be automated?

**Comment by chrisk123999** [comment]
Wall of fire is on my list to look at.  Assuming I get that working well I'll look at the other wall spells too.

**Comment by Fridan99** [comment]
It would be wonderful to have the option of wall spells.

**Comment by Autumn225** [comment]
This request is already on the CPR discord. We are no longer accepting regular feature requests off the github.
