### ISSUE TITLE
[Feature Request] Spell: Flaming Sphere

### ISSUE THREAD

**Issue by GabrielOsvair** [chrisk123999/chris-premades#162]
I use this magic a lot and automation would be great. Currently it is almost perfect, I use a item macro with DIME, which when rolling the warpgate invokes a pre-configured token, and with Active Auras, the token automatically carries out attacks at the beginning of the turn with an effect using the Midi.
```
flags.midi-qol.OverTime

turn=end,saveDC=@attributes.spelldc,saveMagic=true,saveAbility=dex,damageRoll=2d6,damageType=fire,saveDamage=halfdamage,saveRemove=false
```

The only thing left is for the token to be erased when the caster loses concentration or when the timer expires.

**Comment by Autumn225** [comment]
Please make this feature request on the CPR discord server. We are no longer accepting regular feature requests off the github.
