### ISSUE TITLE
[Spell] Sleet Storm

### ISSUE THREAD

**Issue by VasyaM2000** [chrisk123999/chris-premades#163]
The Sleet Storm spell doesn't apply any effects on enemies and doesn't make them pass any saving throws. It looks like the script just wouldn't boot.
All the required modules are totally up-to-date.

**Comment by chrisk123999** [comment]
Check that you have the setting template listener on.

**Comment by VasyaM2000** [comment]
I sure have. For example, Spirit Guardiand from your module work fine for me.

**Comment by chrisk123999** [comment]
Spirit Guardians uses a different setting.

**Comment by VasyaM2000** [comment]
Anyway, every single button in "general" and "spell" windows is on, including template listener.
