### ISSUE TITLE
[Feature Request] Barbarian Path of the Totem Warrior, Specially Wolf Totem Spirit (combat ability)

### ISSUE THREAD

**Issue by aberracus** [chrisk123999/chris-premades#165]
Would be great to have this automation for the barbarian,  the most combat oriented is the wolf one in totem spirit. and that would be great to have, much of them are only for roleplay or outside of combat benefits, so really thers only a bunch of automations needed

**Path of the Totem Warrior**
The[https://www.dndbeyond.com/classes/barbarian#PathoftheTotemWarrior](url)

**Comment by Autumn225** [comment]
Please make this feature request on the CPR discord server. We are no longer accepting regular feature requests off the github.
