### ISSUE TITLE
[Bug] Green-Flame Blade

### ISSUE THREAD

**Issue by MasterCroissant** [chrisk123999/chris-premades#167]
Damage is applied as normal on the target creature, but the extra fire damage doesn't leap to the selected adjacent creature.

This can be replicated with only the required modules.

**Comment by chrisk123999** [comment]
What is the dispositions of the enemies?

**Comment by MasterCroissant** [comment]
![Bug Report - Disposition of Enemies](https://github.com/chrisk123999/chris-premades/assets/124537248/9157110d-cdaa-4908-9030-883915e22560)

**Comment by chrisk123999** [comment]
Is this still an issue for you? I believe a recent Midi-Qol update fixed a bug with damageOnlyWorkflows that was breaking this automation.

**Comment by MasterCroissant** [comment]
Nope, this issue has been resolved with the Midi update
