### ISSUE TITLE
[Feature Request] Evard's Black Tentacles

### ISSUE THREAD

**Issue by MasterCroissant** [chrisk123999/chris-premades#168]
This is one of my players favorite spell. Would be nice to see this implemented one day, since the spell has some technicalities that I am unable to set-up using automations (i.e. how to apply the spell effects to a creature when it enters its area of effect after the spell has been cast). 

There is also a free jb2a animation available for set-up if needed.

**Comment by gambit07** [comment]
> This is one of my players favorite spell. Would be nice to see this implemented one day, since the spell has some technicalities that I am unable to set-up using automations (i.e. how to apply the spell effects to a creature when it enters its area of effect after the spell has been cast). 
> 
> There is also a free jb2a animation available for set-up if needed.

FYI, this spell is in my module Gambits Premades, labeled as Black Tentacles

**Comment by Autumn225** [comment]
This item is included in the module Gambit's Premades. It may be considered to be done by Chris's Premades at a later date. 
 Please make this feature request if needed on the CPR discord server. We are no longer accepting regular feature requests off the github.
