### ISSUE TITLE
Dread Ambusher adds WIS mod to initiative twice

### ISSUE THREAD

**Issue by Spappz** [chrisk123999/chris-premades#169]
Dread Ambusher, the 3rd-level feature for Gloom Stalker (XGE) rangers, has three AEs. The one simply titled "Dread Ambusher" has two changes: one to `system.attributes.init.bonus`, and one to `system attributes.init.total`.

![image](https://github.com/chrisk123999/chris-premades/assets/34202141/93cc0006-ad3f-4510-afc3-33c42db0b435)

The latter. `*.total`, probably shouldn't be there. It results in the bonus being added twice to rolls, but I'm not sure anything else happens that isn't already covered by `*.bonus`!

I would make a PR but I'm not sure how to directly edit LevelDB files 😅

**Comment by chrisk123999** [comment]
Fixed in the next update.
