### ISSUE TITLE
Mirror image

### ISSUE THREAD

**Issue by Quinn-Aetherwood** [chrisk123999/chris-premades#17]
Hello, and thank you for the module. One thing that hasn't worked for me so far over the last month is mirror image. It doesn't roll for any images and the attack goes through like normal on a hit. I have Mirror image turned on in your module and have all your 
prerequisite modules for yours to function.

**Comment by dmaneyapanda** [comment]
It is working fine for me, as an FYI.  I did just update it in the past 12 hours though.

**Comment by dmaneyapanda** [comment]
It should automatically roll a d20 to see if the attack targets a dupe, and then either miss or destroy the dupe depending on how high the attack roll was.

My only enhancement request would be to have the images FX go down from 4 to 3 to 2 images as they are destroyed!

**Comment by Quinn-Aetherwood** [comment]
Hmmmm. I've tested it a few times and I get no message pop up and the attack will always go though with no opposing D20 roll for the images. Wonder what's missing.

**Comment by chrisk123999** [comment]
Could you screenshot the spell details tab?  Need to verify that it's not using the convenient effect name match.

**Comment by Quinn-Aetherwood** [comment]
<img width="529" alt="Chris 1" src="https://user-images.githubusercontent.com/127997499/225470959-0d6390f7-05df-42fc-a094-ab96f4b49e34.png">
<img width="499" alt="chris 2" src="https://user-images.githubusercontent.com/127997499/225471001-a4f4a536-fca1-4459-89c1-00b3061ad2c1.png">
<img width="707" alt="chris 3" src="https://user-images.githubusercontent.com/127997499/225471015-1934d0fd-a712-48f7-ba30-d1a1fb0a497c.png">

I also added in the effects section. There is an empty space where usually the effect would go.

**Comment by chrisk123999** [comment]
That appears correct at first glance.  I'm away from my PC right now so I can't double check I didn't break it in a recent update.  I'll have to get back to you on this.

**Comment by chrisk123999** [comment]
I just noticed you have ASE.  Try disabling that and see if it persists.

**Comment by Quinn-Aetherwood** [comment]
Thanks mate. Tried it with ASE disabled and same thing. No sign of Mirror image proccing.

**Comment by chrisk123999** [comment]
Could you screenshot the effect after it's been placed on a target actor?  Also try pressing the medkit button on the item header first to make sure it's using the correct item setup.

**Comment by Quinn-Aetherwood** [comment]
<img width="722" alt="chris 4" src="https://user-images.githubusercontent.com/127997499/225477030-bc80d569-d73e-4609-bc38-42b40e878fd6.png">


So i pressed the medkit button first, and got the automation prompt. Tested it again with an attack roll and still no proc. This is the effect on the actor after casting Mirror image.

**Comment by chrisk123999** [comment]
Check your midi-qol settings to see if it's set to use Convenient Effects over the item effects.  It appears to not be using the effect on the item.

**Comment by Quinn-Aetherwood** [comment]
Aaaaah. Yup that's the one, mate. I didn't have it on items effects and if absent apply CE. With that change, Mirror image works as intended. DOPE.

**Comment by chrisk123999** [comment]
I'll probably have to add a warning for that on this spell.  CE is always getting in the way of it.
