### ISSUE TITLE
[Feature Request] Aura of Protection

### ISSUE THREAD

**Issue by GregoryWarn** [chrisk123999/chris-premades#171]
In Aura of protection (paladin level 6), I can't change range from feet to meters, so in a map that uses meters the radius of the effect is 10 meter. Using a map in feet it's perfect instead (10 feet).

**Comment by chrisk123999** [comment]
Metric is currently unsupported with this module. You'll find a lot of the automations act weird with metric maps. It's something I need to figure out how to improve in the future.
