### ISSUE TITLE
[Bug] Favored Foe - Extra damage

### ISSUE THREAD

**Issue by MasterCroissant** [chrisk123999/chris-premades#172]
The selection box appears as intended when a creature is hit, however applying Favored Foe does not trigger any additional damage. PC and creatures are affected by the expected active effects without any abnormalities. Leveling up the character to 6th or 14th level does not correct the situation. Attacks go through as normal, but the extra damage is missing from the damage roll.

![Favored Foe - Extra damage missing](https://github.com/chrisk123999/chris-premades/assets/124537248/0f32df05-4d91-4472-b047-b1648e618343)

![Favored Foe - DAE on PC](https://github.com/chrisk123999/chris-premades/assets/124537248/cb352778-ecec-4b3f-bae8-044ef27a41bf)

![Favored Foe - DAE on Creature](https://github.com/chrisk123999/chris-premades/assets/124537248/020456b9-0390-4246-aa92-f71e3723b7e0)

This can be reproduced with only the required modules

DAE v. 11.1.9.
MIDI QOL v. 11.3.12.2

**Comment by chrisk123999** [comment]
You're likely missing the scale on your ranger class.

**Comment by MasterCroissant** [comment]
You're right, my mistake. I'll look into it
