### ISSUE TITLE
Armor of Agathys reflect damage triggers on miss

### ISSUE THREAD

**Issue by pefcs** [chrisk123999/chris-premades#173]
When someone melee attacks the target with Armor of Agathys on, the reflect damage triggers also on miss, not only on hit.

![armor_of_agathys_bug](https://github.com/chrisk123999/chris-premades/assets/118229534/e9163dba-50a4-43b0-86ae-76504618359a)

**Comment by chrisk123999** [comment]
I see the error, I'll have it fixed in the next update.
