### ISSUE TITLE
[Feature Request] Bardic Inspiration - Valor Bard - Combat Inspiration

### ISSUE THREAD

**Issue by k3tw13z3l** [chrisk123999/chris-premades#179]
Feature request: Add a PHB Valor Bard's, Combat Inspiration.

**Comment by tigue54** [comment]
hello, I know it's hard work and thank you, no advance on this capacity?

**Comment by Autumn225** [comment]
Please make this feature request on the CPR discord server. We are no longer accepting regular feature requests off the github.
