### ISSUE TITLE
Issues with Turn Undead

### ISSUE THREAD

**Issue by dmaneyapanda** [chrisk123999/chris-premades#18]
Turn Undead automation is looking great, but I am having a few issues with it:

1- It seems to go through and check every token (or at least enemy) on the scene, which seems inefficient but maybe that's the best way.  

2- But if you have dead tokens around it spams the UI with warnings that some of them are incapacitated.  Including ones nowhere near you.  And even if they are near you, it should probably just ignore anything already at 0 hp.
<img width="206" alt="image" src="https://user-images.githubusercontent.com/2231877/225730580-7886d3f6-525a-42a1-8f1b-54771839e214.png">

2- It is not only affecting undead, it is making all hostile tokens within 30 feet roll saves and suffer the consequences.
<img width="211" alt="image" src="https://user-images.githubusercontent.com/2231877/225732514-d82ac1f7-43b0-4944-80ff-995af954154d.png">

**Comment by chrisk123999** [comment]
I didn't catch that during testing. I'll get it updated in the next release.

**Comment by chrisk123999** [comment]
Just pushed a fix for this.  Not much to be done about it yelling about dead targets.  Midi-qol checks that before I can rewrite the targets.
