### ISSUE TITLE
[Bug] Interaction between Divine Smite and Eldritch Smite

### ISSUE THREAD

**Issue by gantonaci** [chrisk123999/chris-premades#184]
My paladin / warlock has both features automated using your module.

When he attacks first I get a box to select the slot for the Divine Smite or cancel, then another box asking if I wanna use Eldritch Smite.
If I choose to use the pact slot for the Divine Smite and then use the Eldritch Smite both effects happen, but only 1 spell slot is spent.

I tested when I choose a regular spell slot (from the Paladin class) for the Divine Smite and use the Eldritch Smite. In this instance both spell slots are spent correctly.

I did deactivate all modules except those in the required list and the issue persisted.

Thanks for the great module!!

**Comment by chrisk123999** [comment]
Fixed in the next release.
