### ISSUE TITLE
[Feature disappeared] On the tidy sheet, there was a button to update Chris's premade powers for each character. it is gone now.

### ISSUE THREAD

**Issue by gris-x** [chrisk123999/chris-premades#188]
The button allowed to update powers using the latest Cris's premade code. 
Can not see this button update (a small briefcase with a red cross if I remember well)

**Comment by chrisk123999** [comment]
What version of the module are you on?

**Comment by Autumn225** [comment]
Update your Chris's Premades, make sure your DND version is 2.4.1, and that you didn't update DDBI or ItemMacro to their newest versions (which are 3.0 only)

**Comment by gris-x** [comment]
It worked. 
I did not have DDBI installed anymore, and I had updated ItemMacro to the latest, while keeping DnD to 2.4.1
With the versioning indicated above, the medkit is back on my characters' sheets.
thanks!
