### ISSUE TITLE
Bug: Circle of Mortality healing over max

### ISSUE THREAD

**Issue by MotoMoto1234** [chrisk123999/chris-premades#19]
I haven't the time to check if beacon of hope does it too, but Circle of Mortality definitely is healing over the max hps of targets.  

![image](https://user-images.githubusercontent.com/116308065/226145083-5aacbf32-3fbd-4813-ac38-1d12eaeb3082.png)

**Comment by chrisk123999** [comment]
Didn't realize it would let me do that.  I'll limit it to max hp in the
next update.
