### ISSUE TITLE
[Bug] Sneak Attack does not work with Rogue Soulknife Psychic Blades

### ISSUE THREAD

**Issue by zk-sn** [chrisk123999/chris-premades#191]
The Soulknife Psychic Blade should be able to be used with Sneak Attack, but because it's imported as a Class Feature instead of an Item, there is no way to mark it as Finesse.  Thus, the check to see if Sneak Attack should be applied fails because it is not a ranged attack or a finesse item.

**Comment by chrisk123999** [comment]
I don't have any automations for Soulknife. It's likely the D&D Beyond importer doing that. Feel free to make a feature request.

**Comment by LukasPrism** [comment]
I had this same issue. Probably should report it to Mr Primate. At first I used a macro to apply finesse to the feature but later changes to dnd5e prevented that from working. I was using the midi sneak attack at the time and the easiest fix was to modify that to include the psychic blades attack along with finesse and ranged

**Comment by chrisk123999** [comment]
I'll likely just need to include it my sneak attack macro

**Comment by zk-sn** [comment]
Yeah I tried adding the finesse property but it doesn't seem to work.  I'm currently using a workaround where I just made the player an item for his psychic blades instead.

**Comment by chrisk123999** [comment]
DDBI has changed how this feature is imported. It should import as a weapon now.
