### ISSUE TITLE
Unable to enable Chris' Premades

### ISSUE THREAD

**Issue by GameKn1ght** [chrisk123999/chris-premades#195]
I get an error that is a very strange version reference.

![image](https://github.com/chrisk123999/chris-premades/assets/38305774/988e2620-8962-4075-8230-673aa5aea742)

**Comment by chrisk123999** [comment]
The 3.0 update is in beta, you'll want to install the manifest manually: `https://github.com/chrisk123999/chris-premades/releases/download/0.10.7/module.json`
