### ISSUE TITLE
Feature Request - Spell & Ability descriptions

### ISSUE THREAD

**Issue by PointFrankRange** [chrisk123999/chris-premades#20]
When using the D&D Beyond importer to pull in the data from DnDBeyond and it pulls in Chris's Premade items onto the sheet, the original description is overwritten without all the details of the spell or feature.  This makes it difficult to refer to the ability during gameplay, as the player must go to DnDBeyond to read the original description.  It would be hugely helpful if the description details were merged so that the original description is retained with Chris's Premade description appended to the end.

**Comment by chrisk123999** [comment]
When you use the D&D Beyond importer and have the use my premade effects checked it should fill in the description.  You can also copy and paste in descriptions.
