### ISSUE TITLE
[BUG] Stench: Actor with Stench premade is forced to roll save for their own Stench at start of own turn

### ISSUE THREAD

**Issue by Janner3D** [chrisk123999/chris-premades#200]
I'm making a boss monster, and I'm using the Stench premade as a basis to create a Fear Aura similar to the Pit Fiend's. I'm noticing that when I plop Stench onto the actor, whenever it comes around to the start of the source actor's turn, they're being forced to make a save on themselves.

![image](https://github.com/chrisk123999/chris-premades/assets/35965176/f7cb1d73-6e4a-4e2a-a461-dbdaa1fe25d8)

**Comment by Autumn225** [comment]
Does the actor have the immunity passive effect? Did you rename it?
