### ISSUE TITLE
[BUG] Missing actors for Danse Macabre

### ISSUE THREAD

**Issue by kuchrk24** [chrisk123999/chris-premades#201]
FoundryVTT v11.315
DnD 5e v3.03
Chris's Premades v0.10.19

Trying to use the automation for Danse Macabre, but it seems to be looking for actors that do not exist in any of the CPR compendiums. The other summon spells I've tried are working ok.

![image](https://github.com/chrisk123999/chris-premades/assets/74018852/c655f6b6-0600-4e54-9e85-fa6f4e2093b7)

**Comment by kuchrk24** [comment]
Forgot to mention that this was with only Chris's Premades and dependencies active.

**Comment by chrisk123999** [comment]
It's intended for you to make your own. You can rename the Skeleton or Zombie from the srd or ddbi importer.

**Comment by kuchrk24** [comment]
I apologize. I'm trying not to pester you too much. I added some of my own tokens and I'm no longer receiving that error. However I can't seem to get it to work. I am not being prompted to select the desired creatures like the description states. I tried casting the spell with some tokens targeted and with nothing targeted.

**Comment by kuchrk24** [comment]
Disregard. It works when the tokens have the dead status. Thank you for the help.
