### ISSUE TITLE
Having strange interaction with "Reaper" class feature

### ISSUE THREAD

**Issue by DrTravisProthro** [chrisk123999/chris-premades#206]
I have a strange error when using the "Reaper" class feature on one of my player's characters. It does prompt them and me if we would like to use the effect however the box does not give a way to use it. See below,

![image](https://github.com/chrisk123999/chris-premades/assets/52718054/19a28470-37e6-44b2-b3ad-46d964d02af1)

As you can see it provides a prompt box but no way to proceed with the selection. I do not know if I missed anything as I have all the options toggled to enable in the module setting.

An error is generated at the time of the effect, but it may be unrelated. I will post it here for reference.

![image](https://github.com/chrisk123999/chris-premades/assets/52718054/2e6bffe9-80fd-443a-8ef3-20bd6a3a4428)

**Comment by chrisk123999** [comment]
You have another module messing with css most likely. Check with only the minimum requirements.

**Comment by DrTravisProthro** [comment]
Repeated the effect with the same outcome.

Only modules that were active at the time are, 
- Automated Animation
- Build-a-Bonus
- DFreds Convenient Effects
- Dynamic effects (DAE)
- libWrapper
- Sequencer
- Socketlib
- Template Macro
- Times Up
- Token Attacher
- Warp Gate

These are the recommended dependency modules and none other were active and I still get the same result.

**Comment by DrTravisProthro** [comment]
Don't know if this helps but it gives me this when I inspect the element.

![image](https://github.com/chrisk123999/chris-premades/assets/52718054/2969406e-fa94-4d8e-aa3f-3e1cc46d9742)

![image](https://github.com/chrisk123999/chris-premades/assets/52718054/20da366b-6a9c-4637-83f3-9e7f62e69c8e)
