### ISSUE TITLE
Request: Volo's Aasimar "Radiant Soul" feature

### ISSUE THREAD

**Issue by strlys** [chrisk123999/chris-premades#207]
Chris, can you please add the "Volo's Guide to Monsters" variant (the extra damage is the character level instead of their proficiency) to the "Radiant Soul" feature that you already added?

Thank you very much, your module is the best!!!

**Comment by Autumn225** [comment]
Please move this feature request to the CPR discord server, we are no longer accepting regular feature requests off the github. Fair warning, this is unlikely to ever be done since it is legacy content.
