### ISSUE TITLE
Spirit Guardians not being cast and console error

### ISSUE THREAD

**Issue by edoreld** [chrisk123999/chris-premades#208]
Casting the medkit'd version of Spirit Guardians fails and an error is logged to the console.

Test Scenario
1. Have a cleric with the spell "Spirit Guardians"
2. Medkit it
3. Try to cast it

![image](https://github.com/chrisk123999/chris-premades/assets/973854/74a7152a-371a-43bc-990f-16861703754c)

Result:
2 errors are logged to the console
![image](https://github.com/chrisk123999/chris-premades/assets/973854/4df5d40b-a238-44a0-94f9-7b73cfbc0c0f)

When testing with a Spirit Guardians spell that's dragged out of the "DDB Spells" compendium, the spell is cast normally. The following window appears:

![image](https://github.com/chrisk123999/chris-premades/assets/973854/5b15b8a6-6266-4e3c-8e61-c61ebc37edcb)

In the 2nd popup window, a checkbox to create a measured template appears. In the medkit'd version, this prompt doesn't appear.

Environment:
Midi QOL: 11.4.15
Chris' Premades: 0.10.44
D&D 3.1.0
A bunch of other modules

**Comment by chrisk123999** [comment]
D&D 3.1.0 is not supported yet.
