### ISSUE TITLE
[Suggestion] Log Update

### ISSUE THREAD

**Issue by rinnocenti** [chrisk123999/chris-premades#21]
it would be interesting when updating the sheet to have a log of which items were updated, print it in a dialog box or even in the chat

**Comment by chrisk123999** [comment]
I'll see what I can come up with.  Currently it's using the D&D Beyond importer API to handle the swaps, but I can include a list of things it finds too.

**Comment by venom986** [comment]
> it would be interesting when updating the sheet to have a log of which items were updated, print it in a dialog box or even in the chat

Since Chris mentioned he uses the DDBI API for this feature, it's possible that as a workaround you could check console output (F12), as I believe DDBI spits out the names of the "Items" it is processing.
