### ISSUE TITLE
[BUG] Conjure Fey reports "No matching actors found in specified folder" and fails to cast.

### ISSUE THREAD

**Issue by fourdegrees** [chrisk123999/chris-premades#210]
Using the default CPR Spell dragged onto a character from the compendium, this warning fires and nothing is summoned. Importing the spell, putting it on a character, customizing it with a directory similarly fails. All of the other "Conjure X" spells work as expected. I tested turning some modules off/on, but the result is the same. I checked that the game settings directory for Summons is "Chris Premades", I tried putting different directory names, etc. All the other Conjure X spells work, but Conjure Fey does not.

**Comment by Autumn225** [comment]
Sounds like you don't have the actor imported. A button should pop up in chat to import it. You can also go into the CPR Summons compendium and import the relevant actor. Mostly simply, you can turn on the "Keep summon actors updated" setting in the CPR settings under Summons.

**Comment by Autumn225** [comment]
Or are you talking about Conjure Fey? They are two very different spells. If it's conjure fey, you likely don't have fey creatures imported in your specified folder of the appropriate CR.

**Comment by fourdegrees** [comment]
Thank you for the reply. You are correct in that I misspoke. I meant to post about Conjure Fey. 

I do have the Summons folder imported alongside all my other Actors. I can use other Conjure and Summon spells normally. For example, Summon Fey works and goes through the usual prompts (about Fuming, Mirthful, Triksy), and then it places a Fey Sprit actor in the Scene. Conjure Animals, Conjure Celestial, Elemental, Minor Elementals, and Woodland Beings all function normally. I double checked to ensure I have an Actor folder named "Fey" that contains a variety of imported actors that fit the required CR.

**Comment by Autumn225** [comment]
Can you run the troubleshooter from the CPR settings under help and include it here, as well as a screenshot of the folder with the fey actors in it?

**Comment by fourdegrees** [comment]
![image](https://github.com/chrisk123999/chris-premades/assets/8021366/e28a5480-5395-4717-b0ea-9f0ce8bca30f)


/////////////// Game Information ///////////////
Foundry: 11.315
System: 3.1.0
Language: en
Chris's Premades: 0.10.50

/////////////// Required Modules ///////////////
Automated Animations: 4.2.71
Build A Bonus: 11.9.4
Dynamic Active Effects: 11.3.15
DFreds Convenient Effects: 6.0.3
Effect Macro: 11.2.2
libWrapper: 1.12.13.0
Midi-Qol: 11.4.15
Sequencer: 3.1.4
Socketlib: 1.0.13
Template Macro: 11.0.1
Times Up: 11.3.8.1
Token Attacher: v4.5.15
Warpgate: 1.19.2

/////////////// Optional Modules ///////////////
Advanced Token Effects: 0.7.2
About Time: 11.0.1
Animated Spell Effects: Cartoon: 0.4.5 (Disabled)
Custom Character Sheet Sections: 2.0.1
D&D Beyond Importer: 5.1.1
Dice So Nice!: 4.6.10
Simple Calendar: 2.4.13
FXMaster: 4.0.2
Jules&Ben's Animated Assets (F): 0.6.6
Jules&Ben's Animated Assets (P): Missing!
Quick Insert: 2.8.5
Small Time: 1.19.2
Tidy 5e Sheet: 3.0.0
Visual Active Effects: 11.1.3
Universal Animations: Missing!
Gambit's Premades: 0.1.8
Midi Item Showcase - Community: Missing!

/////////////// CPR Settings ///////////////
Automation Verification: true
Breaking Version Change: 9
Tour Message: true
Show Names: true
Priority Queue: true
Item Replacer Access: false
Item Configuration Access: true
Movement Listener: true
Template Listener: true
Keep Summon Actors Updated: true
Minions use caster's initiative: true
Player choose creatures for conjure spells: true
Effect Auras: true
Active Effect Additions: true
Skill Patching: true
Save Patching: true
Automatic VAE Descriptions: true
No NPC VAE Descriptions: false
VAE Temporary Item Buttons: true
Show Limits Animations: true
Use Epic Rolls: false
Blinded and Invisibility Changes: false
LastGM: rTsay3kYY7W9l8OW
Combat Listener: true
Short / Long Rest Listener: true
Movement Triggers: [object Object]
Additional Compendiums: midi-srd.Midi SRD Feats,midi-srd.Midi SRD Spells,midi-srd.Midi SRD Items,midi-qol.midiqol-sample-items
Additional Compendium Priority: [object Object]
Gambit's Premades Support: 1
Midi Item Showcase - Community Support: 0
Personal Item Compendium: world.ddb-descent-into-avernus-ddb-items
Personal Spell Compendium: world.ddb-descent-into-avernus-ddb-spells
Personal Monster Compendium: world.ddb-descent-into-avernus-ddb-monsters
Personal Racial Trait Compendium: world.ddb-descent-into-avernus-ddb-racial-traits
Condition Resistance Mechanic: true
Condition Vulnerability Mechanic: true
Flat Attack Bonus: false
On Hit Automation: true
Beacon of Hope Automation: true
Darkness Automation: true
Fog Cloud Automation: true
Death Ward Automation: true
Elemental Adept Automation: true
Dual Wielder Automation: true
Mirror Image Automation: true
Protection from Evil and Good Automation: true
Sanctuary Automation: true
Ranged Divine Smite: false
Unarmed Strike Divine Smite: false
Critical Roll Table: 
Fumble Roll Table: 
Use Critical Roll Table: 0
Use Fumble Roll Table: 0
DMG Cleave Mechanic: false
DMG Cleave Damaged Tokens: false
Shifter Wildhunt Automation: true
Undead Fortitude Automation: true
Exploding Heals: false
Shield Guardian Automation: true
Warding Bond Automation: true
Attack Listener: true
Magic Missile Toggle: true
Strength of the Grave Automation: true
Relentless Endurance Automation: true
Shadow of Moil Automation: true
Emboldening Bond: true
Manual Rolls: false
Ignore GM Rolls: true
Player Settings: [object Object]
Randomizer: false
Humanoid Randomizer Settings: [object Object]
Dice So Nice Compatability: true
Arcane Ward Automation: true
Righteous Heritor Automation: true
Other Summons Folder: Chris Premades
Item Features: true
Baldur's Gate 3 Weapon Actions: false
Add Generic Actions: npc
 Cast Animations: true
Abjuration Color: blue
Conjuration Color: yellow
Divination Color: blue
Enchantment Color: pink
Evocation Color: red
Illusion Color: purple
Necromancy Color: green
Transmutation Color: yellow
Compelled Duel Automation: true
Colorize Automated Animations Title Bar Button: true
Colorize Build A Bonus Title Bar Button: true
Colorize Dynamic Active Effects Title Bar Button: true
Colorize Template Macro Title Bar Button: true
D&D5E Animations Sounds: true
Build A Bonus Overlapping Effects: true
Aura of Life Spell Automation: true
Booming Blade Automation: true
Manifest Echo Automation: true
Twilight Shroud Automation: true
Display Temporary Effects: 1
Display Sidebar Macros: false
Display Select Tool Everywhere: false
Last Update Check: 1711404749784
Check for Updates: true
Critical Role Firearm Support: true
Dialog Targeting: false
Minor Beneficial Properties Descriptions: [object Object]
Major Beneficial Properties Descriptions: [object Object]
Minor Detrimental Properties Descriptions: [object Object]
Major Detrimental Properties Descriptions: [object Object]
Spells Retain Action Economy: false
Last Backup Time: 1711404749784
Enable Character Backup: false
Compendium: null
Retention Period: 0
Frequency: 79200
Auto Update Summons Initiative: true
Auto Update Companions Initiative: true

/////////////// Midi-Qol Settings ///////////////
Roll Automation Support: true
Apply Convenient Effects: CE > Items
Roll Seperate Attack Per Target: true
Merge Card: true
Actor On Use: true
Item On Use: true
Auto Roll Damage: onHit

/////////////// Warpgate User Permissions ///////////////
Create Tokens: true
Configure Tokens: true
Browse Files: true

**Comment by fourdegrees** [comment]
![image](https://github.com/chrisk123999/chris-premades/assets/8021366/8563e305-525d-44e0-8dce-089e9ba1f2d2)

**Comment by Autumn225** [comment]
Again you're confusing the summon fey and conjure fey spells. My initial response was based on "summon fey'. You need to import the fey actors yourself for conjure fey and the other conjure spells. You're also on 3.1 which isn't supported, you need to turn off core concentration for midi's to work. You apply effects setting is also wrong, it needs to be items then CE. Roll separate attack per target is preferred to be off but that shouldn't matter in this case.

**Comment by fourdegrees** [comment]
I'm sorry for confusing you, but I'm reporting the issue correctly in spite of initially citing the wrong spell. I did update the title of the post to correctly reflect the spell at issue. The problem I am having is that Conjure Fey does not work, whereas all other Conjure spells, and all Summon spells are working. 
![image](https://github.com/chrisk123999/chris-premades/assets/8021366/72b69485-1016-4683-b199-ff8b86b85f47)

Here is Conjure Elemental working as intended with the default imported CPR Actor:
![image](https://github.com/chrisk123999/chris-premades/assets/8021366/22d0481b-feb7-4882-bb87-48cff0146c91)

Here is Conjure Elemental working as intended after configuring the spell to look in my imported actors directory titled "Elementals". You can see it is pulling a list of eligible actors from the directory as it should:
![image](https://github.com/chrisk123999/chris-premades/assets/8021366/0bb572e4-94cd-4ec9-90e1-9cd693bfe70f)

Here is Summon Fey working as intended, using the default imported CPR Actor:
![image](https://github.com/chrisk123999/chris-premades/assets/8021366/f4ec7901-92cb-430b-b4ad-43e5d2127c4b)

So, the issue isn't that Conjure Fey can't find an actor at all (because you can see that another spell that relies on the same imported actor is working fine), the issue seems to be that the spell is looking in the wrong place for actors. Configuring Conjure Fey to set either the default or a custom directory always returns the same error:
![image](https://github.com/chrisk123999/chris-premades/assets/8021366/c7d43704-be50-4d02-8b67-fc185a585278)

Here is me setting my "Fey" directory as the spot Conjure Fey should look:
![image](https://github.com/chrisk123999/chris-premades/assets/8021366/f9e5be74-98a6-4de2-98fe-4ca15f92d974)

And it immediately firing the same error:
![image](https://github.com/chrisk123999/chris-premades/assets/8021366/7f8b7690-04aa-4d7b-827c-80bd5593f724)

**Comment by Autumn225** [comment]
Do you have multiple folders called "Fey"?

**Comment by fourdegrees** [comment]
No. :(
