### ISSUE TITLE
Error: This is not a registered game setting   

### ISSUE THREAD

**Issue by MixmastaGofasta** [chrisk123999/chris-premades#212]
The following code creates an error  as "Character Sheet Hook" is no longer a setting for ItemMacro. 

`       if (game.settings.get('itemacro', 'charsheet')) ui.notifications.error('Chris\'s Premades & Midi-Qol requires "Character Sheet Hook" in Item Macro\'s module settings to be turned off!');`

 Error: This is not a registered game setting   at ClientSettings.get (foundry.js:3339:42) at Object.fn (module.js:92:1)
(anonymous) @ module.js:94
await in (anonymous) (async)
#call @ foundry.js:730
callAll @ foundry.js:687
setupGame @ foundry.js:8746
3forgevtt-module.js:2379 File Uploaded to your Assets Library successfully

**Comment by chrisk123999** [comment]
It's wrapped in a try block so it shouldn't actually break anything.
