### ISSUE TITLE
[BUG] Summon Draconic Spirit (and other summons) - Concentration automation

### ISSUE THREAD

**Issue by MasterCroissant** [chrisk123999/chris-premades#214]
All summoning spells that require concentration fail and prevent placement of token on the canvas.

Unchecking the concentration box on the spell detail sheet resolves the issue.

D&D5e system v.3.1.1. 
Midi QOL v.11.4.15
DAE v.11.3.15
Chris's Premades v.0.10.50

![image](https://github.com/chrisk123999/chris-premades/assets/124537248/0a5555a9-d90b-4c84-a929-014d2244c463)

![image](https://github.com/chrisk123999/chris-premades/assets/124537248/9f2fab06-579d-4fb0-8a29-d6b32f24e8ce)

**Comment by chrisk123999** [comment]
This module doesn't support 3.1 yet.

**Comment by Autumn225** [comment]
Currently for midi on 3.1 you need to disable system concentration in the DND settings, which is stated in midi's patch notes. CPR is not verified for 3.1 as Chris stated.

**Comment by MasterCroissant** [comment]
Yes, I've disabled the system concentration before posting the issue. I'll downgrade to 3.0.4 for the time being. Thanks a lot for the quick reply!
