### ISSUE TITLE
Bug - Error: This is not a registered game setting

### ISSUE THREAD

**Issue by Jonwh25** [chrisk123999/chris-premades#216]
Foundry V11 315
DnD v 3.1.1
Module v - 0.10.54

Getting this in my console log:
![image](https://github.com/chrisk123999/chris-premades/assets/60674327/f2d28f3d-d5f1-4e3b-a84a-53d6eee63416)

If I disable your module, it goes away. I tried each dependency alone and no error. It only appears when yours is loaded.

**Comment by chrisk123999** [comment]
Not an issue as it's an error from a try block. You don't need the item macro module.

**Comment by Jonwh25** [comment]
ah. I think I need it for some of my macros that Crymic did, but noted. Thanks.

**Comment by chrisk123999** [comment]
It's unlikely you specifically need item macro.

**Comment by Jonwh25** [comment]
Ha. Ok. That saves me $3 a month to his patreon then. I'll drop item macro.

**Comment by Autumn225** [comment]
Crymic's macros can be put in the item via DIME, or just imported. Midi will run the macros without item macro.
