### ISSUE TITLE
[BUG] Wild Shape does not work

### ISSUE THREAD

**Issue by Janner3D** [chrisk123999/chris-premades#217]
I've set my preferred personal compendiums in the options, using my own monsters compendium as suggested, but when I use WIld Shape on either a PC or NPC, it does nothing. No prompts appear, and I get this error:
![image](https://github.com/chrisk123999/chris-premades/assets/35965176/05021d29-e87c-432f-9a4f-69b8b53bfdfb)
I also have just the recommended mods installed:
![image](https://github.com/chrisk123999/chris-premades/assets/35965176/59dd4179-303d-40f6-8bed-eed1551f70e8)
![image](https://github.com/chrisk123999/chris-premades/assets/35965176/0e60e1b1-9ec9-4fbc-9c0b-75afba0a2db3)

**Comment by 3DSTyler** [comment]
The error mentions tidy5e, can you try without tidy enabled and see if the results differ?
