### ISSUE TITLE
Cannot be enabled due to issues in required dependencies

### ISSUE THREAD

**Issue by TeoBist** [chrisk123999/chris-premades#220]
Foundry v11.315 (D&D Fifth Edition 3.1.1)

in a new World, with only enabled Chris Premades required modules, Chris Premades cannot be enabled.
Am I doing it wrong?

Thanks in advance :)
<img width="505" alt="image" src="https://github.com/chrisk123999/chris-premades/assets/166062854/5494cd3b-6629-44af-8461-c00f056dfa77">

![image](https://github.com/chrisk123999/chris-premades/assets/166062854/e52a0c0b-397d-44cc-b5b9-057d2043ac65)

**Comment by Meagles7** [comment]
Try installing the "Times Up" module as well.

**Comment by TeoBist** [comment]
> Try installing the "Times Up" module as well.

tried, still not working adding Times Up and other 5 modules


![image](https://github.com/chrisk123999/chris-premades/assets/166062854/da493a7f-9c4b-4502-a7bd-f9999318a144)

**Comment by 3DSTyler** [comment]
If you install/enable Module Management+ you can expand the plugin to see what dependancy it's not happy with.
![image](https://github.com/chrisk123999/chris-premades/assets/117966309/7b307a0d-2350-4ff3-afdc-50aa7905fb32)

**Comment by TeoBist** [comment]
Solved. There was an error with "Token Attacher". After uninstalling and reinstalling TA, I was able to enable Chris's Premade.

Thank you all
