### ISSUE TITLE
Spirit Guardians spell affects tokens that are not touching the AoE

### ISSUE THREAD

**Issue by SilvesTheRog** [chrisk123999/chris-premades#224]
Hi again!
I noticed that Spirit Guardians apply the effect to a token that is standing close to the edge of the 15ft radius. On the image below, the circle doesn't touch some tokens even visually, but they are still affected by the spell. 

![image](https://github.com/chrisk123999/chris-premades/assets/127493227/818600aa-0a5e-4bce-beab-f4869025320f)

**Comment by SagaTympana** [comment]
This is because the affected tokens are within 15 feet of the caster, so they _should_ be affected. The visual is a circle but that’s just aesthetic. Rules-wise, it’ll depend on your diagonal measurement rule.

**Comment by SilvesTheRog** [comment]
Got it, thanks!
