### ISSUE TITLE
Circle of mortality doesn't work

### ISSUE THREAD

**Issue by SilvesTheRog** [chrisk123999/chris-premades#227]
Hello!
I added circle of mortality to a character, but it doesn't work at all, it heals for the rolled result, not the maximum possible. Tried adding the effect to both targets, just in case. 

![image](https://github.com/chrisk123999/chris-premades/assets/127493227/2caf80b1-301e-440c-a1e3-04d055ffe863)

**Comment by Autumn225** [comment]
Please join the discord server to troubleshoot this further, we are unable to reproduce this issue.
