### ISSUE TITLE
Favored By The Gods - Activation Order

### ISSUE THREAD

**Issue by KonteiKeisei** [chrisk123999/chris-premades#23]
FBTG is activating before the caster knows the outcome of the attack roll, Per RAW they are supposed to know if they hit or miss before being prompted.

Ideally, they should only be prompted if they fail a save or miss an attack roll. But even here as it is, its still not giving them the outcome before prompting them in the first place.

Not sure if this is a Midi setting I need to have set a specific way, but I know there are options to prompt only on misses and fails.

**Comment by chrisk123999** [comment]
I'll take a look at this when I get home.

**Comment by chrisk123999** [comment]
Optional Bonus Effects from Mid-Qol doesn't have a way to roll after failing the save or missing with the attack roll.  This is the best implementation of the effect as I can get with the current features from Midi-Qol.

**Comment by chrisk123999** [comment]
Actually, I just found a way to do it.  It wasn't in the Midi-Qol documentation, it'll have it in the next release.
