### ISSUE TITLE
Hail of Thorns isn't working

### ISSUE THREAD

**Issue by shockaman88** [chrisk123999/chris-premades#236]
Applying the automation seems to work. it applies concentration and the hail of thorns buff, but the additional damage and aoe trigger don't happen. The buff and concentration aren't removed after attack.

**Comment by madseumas** [comment]
Seeing the same.

**Comment by chrisk123999** [comment]
I made some small tweaks for the next update, but it doesn't look broken to me. Please provide your CPR troubleshooter here or on the Discord server.

**Comment by madseumas** [comment]
```
/////////////// Game Information ///////////////
Foundry: 11.315
System: 3.1.2
Language: en
Chris's Premades: 0.10.61

/////////////// Required Modules ///////////////
Automated Animations: 4.2.72
Build A Bonus: 11.10.2
Dynamic Active Effects: 11.3.17
DFreds Convenient Effects: 6.0.3
Effect Macro: 11.2.2
libWrapper: 1.12.13.0
Midi-Qol: 11.4.23
Sequencer: 3.1.4
Socketlib: 1.0.13
Template Macro: 11.0.1
Times Up: 11.3.9.1
Token Attacher: v4.5.15
Warpgate: 1.19.2

/////////////// Optional Modules ///////////////
Advanced Token Effects: 0.7.2
About Time: 11.0.1
Animated Spell Effects: Cartoon: Missing!
Custom Character Sheet Sections: Missing!
D&D Beyond Importer: 5.1.15
Dice So Nice!: 4.6.10
Simple Calendar: 2.4.13
FXMaster: 4.0.2
Jules&Ben's Animated Assets (F): 0.6.7
Jules&Ben's Animated Assets (P): Missing!
Quick Insert: 2.8.5 (Disabled)
Small Time: 1.19.2
Tidy 5e Sheet: Missing!
Visual Active Effects: Missing!
Universal Animations: Missing!
Gambit's Premades: Missing!
Midi Item Showcase - Community: Missing!

/////////////// CPR Settings ///////////////
Automation Verification: true
Breaking Version Change: 9
Tour Message: true
Show Names: true
Priority Queue: true
Item Replacer Access: false
Item Configuration Access: false
Movement Listener: false
Template Listener: true
Keep Summon Actors Updated: true
Minions use caster's initiative: true
Player choose creatures for conjure spells: false
Effect Auras: false
Active Effect Additions: true
Skill Patching: false
Save Patching: false
Automatic VAE Descriptions: false
No NPC VAE Descriptions: false
VAE Temporary Item Buttons: false
Show Limits Animations: false
Use Epic Rolls: false
Blinded and Invisibility Changes: false
LastGM: Ku2FkKIHSD2OyuOq
Combat Listener: true
Short / Long Rest Listener: false
Movement Triggers: [object Object]
Additional Compendiums: midi-srd.Midi SRD Feats,midi-srd.Midi SRD Spells,midi-srd.Midi SRD Items,midi-qol.midiqol-sample-items
Additional Compendium Priority: [object Object]
Gambit's Premades Support: 0
Midi Item Showcase - Community Support: 0
Personal Item Compendium: world.ddb-b1b2-ddb-items
Personal Spell Compendium: world.ddb-b1b2-ddb-spells
Personal Monster Compendium: world.ddb-b1b2-ddb-monsters
Personal Racial Trait Compendium: world.ddb-b1b2-ddb-racial-traits
Condition Resistance Mechanic: true
Condition Vulnerability Mechanic: true
Flat Attack Bonus: false
On Hit Automation: false
Beacon of Hope Automation: true
Darkness Automation: true
Fog Cloud Automation: true
Death Ward Automation: true
Elemental Adept Automation: true
Dual Wielder Automation: true
Mirror Image Automation: true
Protection from Evil and Good Automation: true
Sanctuary Automation: true
Ranged Divine Smite: false
Unarmed Strike Divine Smite: false
Critical Roll Table: 
Fumble Roll Table: 
Use Critical Roll Table: 0
Use Fumble Roll Table: 0
DMG Cleave Mechanic: false
DMG Cleave Damaged Tokens: false
Shifter Wildhunt Automation: true
Undead Fortitude Automation: true
Exploding Heals: false
Shield Guardian Automation: true
Warding Bond Automation: true
Attack Listener: false
Magic Missile Toggle: false
Strength of the Grave Automation: true
Relentless Endurance Automation: true
Shadow of Moil Automation: true
Emboldening Bond: true
Manual Rolls: false
Ignore GM Rolls: true
Player Settings: [object Object]
Randomizer: false
Humanoid Randomizer Settings: [object Object]
Dice So Nice Compatability: true
Arcane Ward Automation: true
Righteous Heritor Automation: true
Other Summons Folder: Chris Premades
Item Features: true
Baldur's Gate 3 Weapon Actions: false
Add Generic Actions: none
 Cast Animations: true
Abjuration Color: blue
Conjuration Color: yellow
Divination Color: blue
Enchantment Color: pink
Evocation Color: red
Illusion Color: purple
Necromancy Color: green
Transmutation Color: yellow
Compelled Duel Automation: true
Colorize Automated Animations Title Bar Button: false
Colorize Build A Bonus Title Bar Button: false
Colorize Dynamic Active Effects Title Bar Button: false
Colorize Template Macro Title Bar Button: false
D&D5E Animations Sounds: false
Build A Bonus Overlapping Effects: true
Aura of Life Spell Automation: true
Booming Blade Automation: true
Manifest Echo Automation: true
Twilight Shroud Automation: true
Display Temporary Effects: 1
Display Sidebar Macros: false
Display Select Tool Everywhere: false
Last Update Check: 1713738516588
Check for Updates: true
Critical Role Firearm Support: false
Dialog Targeting: false
Minor Beneficial Properties Descriptions: [object Object]
Major Beneficial Properties Descriptions: [object Object]
Minor Detrimental Properties Descriptions: [object Object]
Major Detrimental Properties Descriptions: [object Object]
Spells Retain Action Economy: false
Last Backup Time: 1713738516588
Enable Character Backup: false
Compendium: null
Retention Period: 0
Frequency: 79200000
Auto Update Summons Initiative: true
Auto Update Companions Initiative: true

/////////////// Midi-Qol Settings ///////////////
Roll Automation Support: true
Apply Convenient Effects: Items > CE
Roll Seperate Attack Per Target: false
Merge Card: true
Actor On Use: true
Item On Use: true
Auto Roll Damage: always

/////////////// Warpgate User Permissions ///////////////
Create Tokens: false
Configure Tokens: false
Browse Files: false
```

**Comment by shockaman88** [comment]
I just updated to the latest version of your mod, and I'm still having an issue. Here's the info from the troubleshooter.

/////////////// Game Information ///////////////
Foundry: 11.315
System: 3.1.2
Language: en
Chris's Premades: 0.10.62

/////////////// Required Modules ///////////////
Automated Animations: 4.2.72
Build A Bonus: 11.10.2
Dynamic Active Effects: 11.3.17
DFreds Convenient Effects: 6.0.3
Effect Macro: 11.2.2
libWrapper: 1.12.13.0
Midi-Qol: 11.4.23
Sequencer: 3.1.4
Socketlib: 1.0.13
Template Macro: 11.0.1
Times Up: 11.3.9.1
Token Attacher: v4.5.15
Warpgate: 1.19.2

/////////////// Optional Modules ///////////////
Advanced Token Effects: 0.7.2
About Time: 11.0.1
Animated Spell Effects: Cartoon: Missing!
Custom Character Sheet Sections: Missing!
D&D Beyond Importer: 5.1.15
Dice So Nice!: 4.6.10
Simple Calendar: 2.4.13
FXMaster: 4.0.2
Jules&Ben's Animated Assets (F): Missing!
Jules&Ben's Animated Assets (P): 0.6.3
Quick Insert: 2.8.5
Small Time: Missing!
Tidy 5e Sheet: 3.3.1
Visual Active Effects: Missing!
Universal Animations: Missing!
Gambit's Premades: 0.1.20
Midi Item Showcase - Community: Missing!

/////////////// CPR Settings ///////////////
Automation Verification: true
Breaking Version Change: 9
Tour Message: true
Show Names: true
Priority Queue: true
Item Replacer Access: false
Item Configuration Access: true
Movement Listener: true
Template Listener: true
Keep Summon Actors Updated: true
Minions use caster's initiative: true
Player choose creatures for conjure spells: true
Effect Auras: true
Active Effect Additions: true
Skill Patching: true
Save Patching: true
Automatic VAE Descriptions: false
No NPC VAE Descriptions: false
VAE Temporary Item Buttons: false
Show Limits Animations: false
Use Epic Rolls: false
Blinded and Invisibility Changes: false
LastGM: 6XFSAKhwkH5TULP9
Combat Listener: true
Short / Long Rest Listener: true
Movement Triggers: [object Object]
Additional Compendiums: midi-srd.Midi SRD Feats,midi-srd.Midi SRD Spells,midi-srd.Midi SRD Items,midi-qol.midiqol-sample-items
Additional Compendium Priority: [object Object]
Gambit's Premades Support: 2
Midi Item Showcase - Community Support: 0
Personal Item Compendium: world.ddb-tomb-of-annihilation-copy-8-22-ddb-items
Personal Spell Compendium: world.ddb-tomb-of-annihilation-copy-8-22-ddb-spells
Personal Monster Compendium: world.ddb-tomb-of-annihilation-copy-8-22-ddb-monsters
Personal Racial Trait Compendium: world.ddb-tomb-of-annihilation-copy-8-22-ddb-racial-traits
Condition Resistance Mechanic: false
Condition Vulnerability Mechanic: false
Flat Attack Bonus: false
On Hit Automation: true
Beacon of Hope Automation: true
Darkness Automation: true
Fog Cloud Automation: true
Death Ward Automation: true
Elemental Adept Automation: false
Dual Wielder Automation: false
Mirror Image Automation: true
Protection from Evil and Good Automation: true
Sanctuary Automation: true
Ranged Divine Smite: false
Unarmed Strike Divine Smite: false
Critical Roll Table: 
Fumble Roll Table: 
Use Critical Roll Table: 0
Use Fumble Roll Table: 0
DMG Cleave Mechanic: false
DMG Cleave Damaged Tokens: false
Shifter Wildhunt Automation: false
Undead Fortitude Automation: true
Exploding Heals: false
Shield Guardian Automation: true
Warding Bond Automation: true
Attack Listener: true
Magic Missile Toggle: false
Strength of the Grave Automation: false
Relentless Endurance Automation: false
Shadow of Moil Automation: true
Emboldening Bond: false
Manual Rolls: false
Ignore GM Rolls: true
Player Settings: [object Object]
Randomizer: false
Humanoid Randomizer Settings: [object Object]
Dice So Nice Compatability: true
Arcane Ward Automation: false
Righteous Heritor Automation: false
Other Summons Folder: Chris Premades
Item Features: true
Baldur's Gate 3 Weapon Actions: false
Add Generic Actions: none
 Cast Animations: true
Abjuration Color: blue
Conjuration Color: yellow
Divination Color: blue
Enchantment Color: pink
Evocation Color: red
Illusion Color: purple
Necromancy Color: green
Transmutation Color: yellow
Compelled Duel Automation: true
Colorize Automated Animations Title Bar Button: false
Colorize Build A Bonus Title Bar Button: false
Colorize Dynamic Active Effects Title Bar Button: false
Colorize Template Macro Title Bar Button: false
D&D5E Animations Sounds: false
Build A Bonus Overlapping Effects: true
Aura of Life Spell Automation: true
Booming Blade Automation: true
Manifest Echo Automation: true
Twilight Shroud Automation: false
Display Temporary Effects: 0
Display Sidebar Macros: false
Display Select Tool Everywhere: false
Last Update Check: 1713748354565
Check for Updates: true
Critical Role Firearm Support: false
Dialog Targeting: false
Minor Beneficial Properties Descriptions: [object Object]
Major Beneficial Properties Descriptions: [object Object]
Minor Detrimental Properties Descriptions: [object Object]
Major Detrimental Properties Descriptions: [object Object]
Spells Retain Action Economy: false
Last Backup Time: 1713748354565
Enable Character Backup: false
Compendium: null
Retention Period: 0
Frequency: 79200
Auto Update Summons Initiative: false
Auto Update Companions Initiative: false

/////////////// Midi-Qol Settings ///////////////
Roll Automation Support: true
Apply Convenient Effects: Items > CE
Roll Seperate Attack Per Target: false
Merge Card: true
Actor On Use: true
Item On Use: true
Auto Roll Damage: none

/////////////// Warpgate User Permissions ///////////////
Create Tokens: true
Configure Tokens: true
Browse Files: false

/////////////// Other ///////////////
Unsupported Importer: true

**Comment by madseumas** [comment]
I was able to spend some more time trying to debug.  I did find the console was generating a warning.

![console](https://github.com/chrisk123999/chris-premades/assets/6942993/d48799aa-97b3-41f6-be77-8f3bfc074eaf)

I also disabled all modules, restarted, then enabled only Chris's premades (along with all of the required modules it specified).  Same behavior, and the same message.

**Comment by madseumas** [comment]
Culprit in the end was having the DnD5e concentration automation turned on.  Disabled that, re-enabled Midi-Qol's concentration automation and is now working as intended.  Sorry for the waste of time, I'm not even sure how it was turned on and Midi's disabled.
