### ISSUE TITLE
Conflict with Automated Animations Misty Step

### ISSUE THREAD

**Issue by KonteiKeisei** [chrisk123999/chris-premades#24]
Receive the following error isntead of being prompted to select a spot for the actor to teleport to.

![image](https://user-images.githubusercontent.com/49371326/227743393-1909f055-d0a0-4e97-866d-bd8cef62a813.png)

**Comment by chrisk123999** [comment]
Assuming you're on the latest version you need to replace  any of my automations with the new ones.

**Comment by KonteiKeisei** [comment]
same error after hitting the apply all option in character sheet heading.

**Comment by KonteiKeisei** [comment]
Got this when doing that though:

![image](https://user-images.githubusercontent.com/49371326/227744461-1a3794f8-5454-41a4-b1a4-b782372a85d9.png)

**Comment by chrisk123999** [comment]
Try doing it on the items.  The actor updater relies on the ddb importer and must still have some bugs.

**Comment by KonteiKeisei** [comment]
Got it, understood and all fixed. Good luck with the DDB stuff!
