### ISSUE TITLE
Wrath of the Storm - not showing as reaction 

### ISSUE THREAD

**Issue by StevenEvans1966** [chrisk123999/chris-premades#25]
Wrath of the Storm is not automatically showing as a reaction to damage, has to be manually rolled.  This may be a issue with midi-qol

Steps to duplicate.
   Attack and hit a actor with Wrath of the Storm - expected result dialog asking to to use it as a reaction

**Comment by chrisk123999** [comment]
This feature is set as a manual reaction by default.  You can change it to a regular reaction by editing the feature and selecting "Reaction" in the activation cost dropdown box.
