### ISSUE TITLE
Concentration check with Wild Shape

### ISSUE THREAD

**Issue by pefcs** [chrisk123999/chris-premades#255]
When the druid uses the feat Wild Shape, and concentrating, they have to roll a concentration check if the form they are changing has lower HP than themselves, as the HP decrease is considered as damage. Also when reverting from shape, in case their HP is lower than the shape HP, they again are forced to roll a concentration check.

To reproduce the issue:
- use a concentration spell before switching to form (eg.: Barkskin)
- change form to a lower HP beast
- constitution check is started (if it's set in Midi-QoL, but usually it is) - NOK
- switch back to human form
- use a concentration spell, if the previous check failed
- change to a higher HP beast
- revert form
- constitution check is started - NOK

Behavior is the same with DnD5e concentration and with Midi-QoL concentration also. 
Foundry version: v11
DnD5e version: 3.2
CPR version: 0.11.4

![image](https://github.com/chrisk123999/chris-premades/assets/118229534/6d598b5d-c159-40f7-bd84-6ce793848418)

**Comment by roth-michael** [comment]
Works now in v12.
