### ISSUE TITLE
Aura of Warding resists all magical damage not just spells

### ISSUE THREAD

**Issue by candles1202** [chrisk123999/chris-premades#256]
**Issue location:**
scripts/macros/classFeatures/paladin/oathOfTheAncients/auraOfWarding.js
```
'changes': [
            {
                'key': 'system.traits.dr.custom',
                'mode': 2,
                'value': 'Magical Damage',
                'priority': 20
            }
        ],
```

**Testing:**
Tested using a spell attack (thorn whip) and a magical weapon attack (+1 dagger) both have their damage reduce by half. 
I believe the value needs to be updated to something else, but I can't determine what (or if the 'correct' answer exists). I also tried using flags.midi-qol.DR.msak and flags.midi-qol.DR.rsak, but these seem to only take flat values (5, -5, etc) and not multipliers.

**Desired outcome:**
Only spell damage is resisted, not all magical damage. (Thorn whip damage is halved, +1 dagger damage is not).

**Comment by Autumn225** [comment]
Foundry doesn't have a distinction on damage resistance between magic damage from spells and magic damage from weapons, it would have to be coded manually.

**Comment by chrisk123999** [comment]
This will get looked at after the V12 refactor, I'll have replace it with something better.

**Comment by Autumn225** [comment]
Should be correct in v12.
