### ISSUE TITLE
QUESTION: Does dependency on DDB module also REQUIRE me to have a DDB account?

### ISSUE THREAD

**Issue by dstein766** [chrisk123999/chris-premades#26]
Regarding  https://github.com/chrisk123999/chris-premades/issues/24#issuecomment-1483932893

I have noticed this, too and my question is simply this: Does the requirement to install DDB Importer also REQUIRE me to have a DDB account, or is your mod simply leveraging code already in the DDB module?  I have essentially ignored the above issue on the assumption that this feature wasn't working because my DDB module isn't config'ed to use my (non-existent) DDB account.  If I can look forward to this all working at some future date w/o being a DDB customer I'm going to be really pleased.

BTW: REALLY appreciate the work you're doing - and really love your change notes.  I'm never in doubt about what each release is offering!

**Comment by chrisk123999** [comment]
The ddb importer module is an optional requirement.  If it's detected you will get an additional feature on actors to update all the items on the actor with mine.  This function relies on the ddb importer API.  All it's really doing is running the function listed from [here](https://github.com/MrPrimate/ddb-importer/blob/main/FAQ.md#can-i-apply-chriss-premade-effects-to-an-imported-actor).
