### ISSUE TITLE
Post Damage Roll macros not working (Ex: Hex, Sneak Attack)

### ISSUE THREAD

**Issue by IggydB** [chrisk123999/chris-premades#261]
For the life of me, with D&D5E v3.2.1, I cannot get any abilities to roll after damage for additional damage. (For example, The Hex spell and Sneak Attack)

I have a feeling something is preventing them from properly flagging the "Post Damage roll" flag and preventing them from working. Maybe there is a setting stopping this somewhere but if so I cannot find it.

/////////////// Game Information ///////////////
Foundry: 11.315
System: 3.2.1
Language: en
Chris's Premades: 0.11.8

/////////////// Required Modules ///////////////
Automated Animations: 4.2.72
Build A Bonus: 11.11.1
Dynamic Active Effects: 11.3.30.1
DFreds Convenient Effects: 6.0.3
Effect Macro: 11.2.2
libWrapper: 1.12.13.1
Midi-Qol: 11.4.36
Sequencer: 3.2.0
Socketlib: 1.0.13
Template Macro: 11.0.1
Times Up: 11.3.12
Token Attacher: v4.5.15
Warpgate: 1.closing

/////////////// Optional Modules ///////////////
Advanced Token Effects: v0.8.0
About Time: Missing!
Animated Spell Effects: Cartoon: Missing!
Custom Character Sheet Sections: Missing!
D&D Beyond Importer: 5.2.18
Dice So Nice!: 4.6.10
Simple Calendar: 2.4.18 (Disabled)
FXMaster: 4.0.2
Jules&Ben's Animated Assets (F): Missing!
Jules&Ben's Animated Assets (P): 0.6.7
Quick Insert: Missing!
Small Time: Missing!
Tidy 5e Sheet: 4.3.0 (Disabled)
Visual Active Effects: Missing!
Universal Animations: Missing!
Gambit's Premades: 0.1.69 (Disabled)
Midi Item Showcase - Community: Missing!

/////////////// CPR Settings ///////////////
🌎 Automation Verification: true
🌎 Breaking Version Change: 9
🌎 Tour Message: true
🌎 Show Names: true
🌎 Priority Queue: true
🌎 Item Replacer Access: false
🌎 Item Configuration Access: false
🌎 Movement Listener: true
🌎 Template Listener: true
🌎 Keep Summon Actors Updated: true
🌎 Minions use caster's initiative: true
🌎 Player choose creatures for conjure spells: false
🌎 Effect Auras: true
🌎 Active Effect Additions: true
🌎 Skill Patching: true
🌎 Save Patching: true
🌎 Automatic VAE Descriptions: false
🌎 No NPC VAE Descriptions: false
🌎 VAE Temporary Item Buttons: false
🌎 Show Limits Animations: false
🌎 Use Epic Rolls: false
🌎 Blinded and Invisibility Changes: false
🌎 LastGM: lLmUiTggONdGVTkW
🌎 Combat Listener: true
🌎 Short / Long Rest Listener: true
🌎 Movement Triggers: [object Object]
🌎 Additional Compendiums: midi-srd.Midi SRD Feats,midi-srd.Midi SRD Spells,midi-srd.Midi SRD Items,midi-qol.midiqol-sample-items
🌎 Additional Compendium Priority: [object Object]
🌎 Gambit's Premades Support: 0
🌎 Midi Item Showcase - Community Support: 0
🌎 Personal Item Compendium: world.ddb-lmop-shattered-obelisk-ddb-items
🌎 Personal Spell Compendium: world.ddb-lmop-shattered-obelisk-ddb-spells
🌎 Personal Monster Compendium: world.ddb-lmop-shattered-obelisk-ddb-monsters
🌎 Personal Racial Trait Compendium: world.ddb-lmop-shattered-obelisk-ddb-racial-traits
🌎 Condition Resistance Mechanic: false
🌎 Condition Vulnerability Mechanic: false
🌎 Flat Attack Bonus: false
🌎 On Hit Automation: true
🌎 Beacon of Hope Automation: false
🌎 Darkness Automation: false
🌎 Fog Cloud Automation: false
🌎 Death Ward Automation: false
🌎 Elemental Adept Automation: false
🌎 Dual Wielder Automation: false
🌎 Mirror Image Automation: false
🌎 Protection from Evil and Good Automation: false
🌎 Sanctuary Automation: false
🌎 Ranged Divine Smite: false
🌎 Unarmed Strike Divine Smite: false
🌎 Critical Roll Table: 
🌎 Fumble Roll Table: 
🌎 Use Critical Roll Table: 0
🌎 Use Fumble Roll Table: 0
🌎 DMG Cleave Mechanic: false
🌎 DMG Cleave Damaged Tokens: false
🌎 Shifter Wildhunt Automation: false
🌎 Undead Fortitude Automation: true
🌎 Exploding Heals: false
🌎 Shield Guardian Automation: false
🌎 Warding Bond Automation: false
🌎 Attack Listener: true
🌎 Magic Missile Toggle: false
🌎 Strength of the Grave Automation: false
🌎 Relentless Endurance Automation: false
🌎 Shadow of Moil Automation: false
🌎 Emboldening Bond: false
🌎 Manual Rolls: false
🌎 Ignore GM Rolls: false
🌎 Player Settings: [object Object]
🌎 Randomizer: false
🌎 Humanoid Randomizer Settings: [object Object]
🌎 Dice So Nice Compatibility: true
🌎 Arcane Ward Automation: false
🌎 Righteous Heritor Automation: false
🌎 Other Summons Folder: Chris Premades
🌎 Item Features: true
🌎 Baldur's Gate 3 Weapon Actions: false
🌎 Add Generic Actions: none
🌎  Cast Animations: false
👤 Abjuration Color: blue
👤 Conjuration Color: yellow
👤 Divination Color: blue
👤 Enchantment Color: pink
👤 Evocation Color: red
👤 Illusion Color: purple
👤 Necromancy Color: green
👤 Transmutation Color: yellow
🌎 Compelled Duel Automation: false
🌎 Colorize Automated Animations Title Bar Button: false
🌎 Colorize Build A Bonus Title Bar Button: false
🌎 Colorize Dynamic Active Effects Title Bar Button: false
🌎 Colorize Template Macro Title Bar Button: false
🌎 D&D5E Animations Sounds: false
🌎 Build A Bonus Overlapping Effects: true
🌎 Spotlight Omnisearch Summons: false
🌎 Aura of Life Spell Automation: false
🌎 Booming Blade Automation: false
🌎 Globe of Invulnerability Automation: false
🌎 Manifest Echo Automation: false
🌎 Twilight Shroud Automation: false
🌎 Display Temporary Effects: 0
🌎 Display Sidebar Macros: false
🌎 Display Select Tool Everywhere: false
🌎 Active Effect Interface (Experimental): false
🌎 Last Update Check: 1718661159446
🌎 Check for Updates: true
🌎 Critical Role Firearm Support: false
🌎 Dialog Targeting: false
🌎 Minor Beneficial Properties Descriptions: [object Object]
🌎 Major Beneficial Properties Descriptions: [object Object]
🌎 Minor Detrimental Properties Descriptions: [object Object]
🌎 Major Detrimental Properties Descriptions: [object Object]
🌎 Spells Retain Action Economy: false
🌎 Last Backup Time: 1718661159446
🌎 Enable Character Backup: false
🌎 Compendium: null
🌎 Retention Period: 0
🌎 Frequency: 79200
🌎 Auto Update Summons Initiative: true
🌎 Auto Update Companions Initiative: true
🌎 Eldritch Cannon - Fortified Position: false

/////////////// Midi-Qol Settings ///////////////
Roll Automation Support: true
Apply Convenient Effects: Items > CE
Roll Seperate Attack Per Target: false
Merge Card: true
Actor On Use: true
Item On Use: true
Auto Roll Damage: none

/////////////// Warpgate User Permissions ///////////////
Create Tokens: false
Configure Tokens: false
Browse Files: false

**Comment by chrisk123999** [comment]
Auto roll damage needs to be either when needed or always.

**Comment by chrisk123999** [comment]
Please provide your CPR troubleshooter, it's likely the same issue. You must have auto roll damage set to either when needed or always.

**Comment by IggydB** [comment]
> Auto roll damage needs to be either when needed or always.

Updated but still nothing. For Sneak attack, I roll attack, then damage prompt comes up automatically and rolls damage but doesn't auto-apply since it waits for me to press button to apply damage. I think that is where it is getting mixed up, am I missing another setting?
![image](https://github.com/chrisk123999/chris-premades/assets/143030784/e1e8e1ac-f0fe-47a9-8489-f03104660da6)


/////////////// Game Information ///////////////
Foundry: 11.315
System: 3.2.1
Language: en
Chris's Premades: 0.11.8

/////////////// Required Modules ///////////////
Automated Animations: 4.2.72
Build A Bonus: 11.11.1
Dynamic Active Effects: 11.3.30.1
DFreds Convenient Effects: 6.0.3
Effect Macro: 11.2.2
libWrapper: 1.12.13.1
Midi-Qol: 11.4.36
Sequencer: 3.2.0
Socketlib: 1.0.13
Template Macro: 11.0.1
Times Up: 11.3.12
Token Attacher: v4.5.15
Warpgate: 1.closing

/////////////// Optional Modules ///////////////
Advanced Token Effects: v0.8.0
About Time: Missing!
Animated Spell Effects: Cartoon: Missing!
Custom Character Sheet Sections: Missing!
D&D Beyond Importer: 5.2.18
Dice So Nice!: 4.6.10
Simple Calendar: 2.4.18 (Disabled)
FXMaster: 4.0.2
Jules&Ben's Animated Assets (F): Missing!
Jules&Ben's Animated Assets (P): 0.6.7
Quick Insert: Missing!
Small Time: Missing!
Tidy 5e Sheet: 4.3.0 (Disabled)
Visual Active Effects: Missing!
Universal Animations: Missing!
Gambit's Premades: 0.1.69
Midi Item Showcase - Community: Missing!

/////////////// CPR Settings ///////////////
🌎 Automation Verification: true
🌎 Breaking Version Change: 9
🌎 Tour Message: true
🌎 Show Names: true
🌎 Priority Queue: true
🌎 Item Replacer Access: false
🌎 Item Configuration Access: false
🌎 Movement Listener: true
🌎 Template Listener: true
🌎 Keep Summon Actors Updated: true
🌎 Minions use caster's initiative: true
🌎 Player choose creatures for conjure spells: false
🌎 Effect Auras: true
🌎 Active Effect Additions: true
🌎 Skill Patching: true
🌎 Save Patching: true
🌎 Automatic VAE Descriptions: false
🌎 No NPC VAE Descriptions: false
🌎 VAE Temporary Item Buttons: false
🌎 Show Limits Animations: false
🌎 Use Epic Rolls: false
🌎 Blinded and Invisibility Changes: false
🌎 LastGM: lLmUiTggONdGVTkW
🌎 Combat Listener: true
🌎 Short / Long Rest Listener: true
🌎 Movement Triggers: [object Object]
🌎 Additional Compendiums: midi-srd.Midi SRD Feats,midi-srd.Midi SRD Spells,midi-srd.Midi SRD Items,midi-qol.midiqol-sample-items
🌎 Additional Compendium Priority: [object Object]
🌎 Gambit's Premades Support: 1
🌎 Midi Item Showcase - Community Support: 3
🌎 Personal Item Compendium: world.ddb-lmop-shattered-obelisk-ddb-items
🌎 Personal Spell Compendium: world.ddb-lmop-shattered-obelisk-ddb-spells
🌎 Personal Monster Compendium: world.ddb-lmop-shattered-obelisk-ddb-monsters
🌎 Personal Racial Trait Compendium: world.ddb-lmop-shattered-obelisk-ddb-racial-traits
🌎 Condition Resistance Mechanic: false
🌎 Condition Vulnerability Mechanic: false
🌎 Flat Attack Bonus: false
🌎 On Hit Automation: true
🌎 Beacon of Hope Automation: false
🌎 Darkness Automation: false
🌎 Fog Cloud Automation: false
🌎 Death Ward Automation: false
🌎 Elemental Adept Automation: false
🌎 Dual Wielder Automation: false
🌎 Mirror Image Automation: false
🌎 Protection from Evil and Good Automation: false
🌎 Sanctuary Automation: false
🌎 Ranged Divine Smite: false
🌎 Unarmed Strike Divine Smite: false
🌎 Critical Roll Table: 
🌎 Fumble Roll Table: 
🌎 Use Critical Roll Table: 0
🌎 Use Fumble Roll Table: 0
🌎 DMG Cleave Mechanic: false
🌎 DMG Cleave Damaged Tokens: false
🌎 Shifter Wildhunt Automation: false
🌎 Undead Fortitude Automation: true
🌎 Exploding Heals: false
🌎 Shield Guardian Automation: false
🌎 Warding Bond Automation: false
🌎 Attack Listener: true
🌎 Magic Missile Toggle: false
🌎 Strength of the Grave Automation: false
🌎 Relentless Endurance Automation: false
🌎 Shadow of Moil Automation: false
🌎 Emboldening Bond: false
🌎 Manual Rolls: false
🌎 Ignore GM Rolls: false
🌎 Player Settings: [object Object]
🌎 Randomizer: false
🌎 Humanoid Randomizer Settings: [object Object]
🌎 Dice So Nice Compatibility: true
🌎 Arcane Ward Automation: false
🌎 Righteous Heritor Automation: false
🌎 Other Summons Folder: Chris Premades
🌎 Item Features: true
🌎 Baldur's Gate 3 Weapon Actions: false
🌎 Add Generic Actions: none
🌎  Cast Animations: false
👤 Abjuration Color: blue
👤 Conjuration Color: yellow
👤 Divination Color: blue
👤 Enchantment Color: pink
👤 Evocation Color: red
👤 Illusion Color: purple
👤 Necromancy Color: green
👤 Transmutation Color: yellow
🌎 Compelled Duel Automation: false
🌎 Colorize Automated Animations Title Bar Button: false
🌎 Colorize Build A Bonus Title Bar Button: false
🌎 Colorize Dynamic Active Effects Title Bar Button: false
🌎 Colorize Template Macro Title Bar Button: false
🌎 D&D5E Animations Sounds: false
🌎 Build A Bonus Overlapping Effects: true
🌎 Spotlight Omnisearch Summons: false
🌎 Aura of Life Spell Automation: false
🌎 Booming Blade Automation: false
🌎 Globe of Invulnerability Automation: false
🌎 Manifest Echo Automation: false
🌎 Twilight Shroud Automation: false
🌎 Display Temporary Effects: 0
🌎 Display Sidebar Macros: false
🌎 Display Select Tool Everywhere: false
🌎 Active Effect Interface (Experimental): false
🌎 Last Update Check: 1718670141034
🌎 Check for Updates: true
🌎 Critical Role Firearm Support: false
🌎 Dialog Targeting: false
🌎 Minor Beneficial Properties Descriptions: [object Object]
🌎 Major Beneficial Properties Descriptions: [object Object]
🌎 Minor Detrimental Properties Descriptions: [object Object]
🌎 Major Detrimental Properties Descriptions: [object Object]
🌎 Spells Retain Action Economy: false
🌎 Last Backup Time: 1718670141034
🌎 Enable Character Backup: false
🌎 Compendium: null
🌎 Retention Period: 0
🌎 Frequency: 79200
🌎 Auto Update Summons Initiative: true
🌎 Auto Update Companions Initiative: true
🌎 Eldritch Cannon - Fortified Position: false

/////////////// Midi-Qol Settings ///////////////
Roll Automation Support: true
Apply Convenient Effects: Items > CE
Roll Seperate Attack Per Target: false
Merge Card: true
Actor On Use: true
Item On Use: true
Auto Roll Damage: always

/////////////// Warpgate User Permissions ///////////////
Create Tokens: false
Configure Tokens: false
Browse Files: false

**Comment by chrisk123999** [comment]
I'd recommend joining the support channel on the Discord to narrow down the issue better. As you may have some midi-qol settings set in ways that are not supported.

**Comment by IggydB** [comment]
> I have this same problem. Week after week, players cannot seem to utilize features like Divine Smite or Sneak Attack. They never receive any prompt (when I remember a time previously when they had)

Found it., had to have autocheck on attacks hitting. One setting I kept missing. 

![image](https://github.com/chrisk123999/chris-premades/assets/143030784/70a3464d-d785-40d1-a79f-6ee79984bb19)
