### ISSUE TITLE
Drake Companion Summon ignores token art

### ISSUE THREAD

**Issue by KellethDregar** [chrisk123999/chris-premades#267]
For some reason when performing the summon it seems to ignore the token art in the configuration. The avatar art seems to work normally. It appears for a brief moment when dropping then goes to default token image. When checking on the sheet it looks like the avatar sheet was applied but the token wasn't.

![image](https://github.com/user-attachments/assets/7c9e68c5-5405-46af-b7ab-24087d583fd9)
![image](https://github.com/user-attachments/assets/63409b42-e962-458a-9503-19c723f56bc8)
![image](https://github.com/user-attachments/assets/8baaba59-2daf-4900-9b30-b803db357f32)
![image](https://github.com/user-attachments/assets/3e0c1b9b-71eb-441f-9886-d595ea6dd176)

**Comment by chrisk123999** [comment]
You likely have another module changing token images on drop.

**Comment by KellethDregar** [comment]
Huh, alright will try to find the culprit to see if it works. Seeing this error during the workflow:

![image](https://github.com/user-attachments/assets/99f7a5ee-5a4b-40e2-911b-5ad42d4b3bcf)

**Comment by chrisk123999** [comment]
That appears to be an error in the Sequencer module.

**Comment by KellethDregar** [comment]
Seems one of my modules was updated and added a new functionality with token art when a token is placed/created, disabling that option seems to have fixed it. Thanks!
