### ISSUE TITLE
[suggestion] Adding tools to manage updating actor items with Chris Premades

### ISSUE THREAD

**Issue by franckflo** [chrisk123999/chris-premades#27]
Right now, it seems that updating each item supported by Chris Premades is a fairly manual process. It would be awesome if you could add a tool (macro, button in the UI) that would scan selected tokens/actors for items/features that are supported by your module and offer to automatically convert them to Chris Premades items. This could also be used to upgrade tokens/actors with newer versions of your items as well. That would save GMs a lot of time when preparing things!

Thanks for your hard work!

**Comment by chrisk123999** [comment]
If you're using the D&D Beyond importer, there is a setting that uses my automations when it detects them.  Otherwise you can always use the med kit icon on the title bar of the items to quickly replace that specific item.

I do intend to eventually make my own per-actor updater.
