### ISSUE TITLE
Module Settings Missing 0.11.13

### ISSUE THREAD

**Issue by XXDarrienX** [chrisk123999/chris-premades#270]
After updating to 0.11.13 the module settings button disappeared from the Configuration Settings in Foundry, when I downgraded to 0.11.12 its back

![image](https://github.com/user-attachments/assets/55d92f23-9b82-4064-9081-42640a760f50)
![image](https://github.com/user-attachments/assets/9e557c86-f475-4e7d-821f-e44145db020c)

**Comment by chrisk123999** [comment]
That normally only happens if the module fails to load. Check your console after loading in and look for errors.

**Comment by XXDarrienX** [comment]
Even if all the compendiums are still there?

**Comment by chrisk123999** [comment]
Yes

**Comment by chrisk123999** [comment]
If a dependent module doesn't load it may be causing CPR to also fail to load. Please provide your console log.

**Comment by XXDarrienX** [comment]
https://paste.ofcode.org/3btMuGQC3UMTXqF5PHQKbAc

**Comment by chrisk123999** [comment]
You may want to downgrade your Midi-Qol version. I'm don't see anything obvious that would be causing it to not load. The Midi-Qol Discord server may be better able to help you track down those Midi-Qol errors.

**Comment by XXDarrienX** [comment]
Strange because the the version before 0.11.13 works, but I will check with Midi
