### ISSUE TITLE
Cast animation is distorted when using hex grid

### ISSUE THREAD

**Issue by crlgn** [chrisk123999/chris-premades#271]
When using hex grid, the cast animation intro is distorted because the asset stretches with tile width and height. 
According to Sequencer docs, the issue is fixed by adding `{uniform:true}` to the scaleToObject() call.

````
.scaleToObject(2, {uniform:true})
````

Example image: 
<img width="384" alt="image" src="https://github.com/user-attachments/assets/d42e5390-d681-4577-b267-725a4a7cd719">

**Comment by Autumn225** [comment]
This feature won't be ported to the v12 version but will likely be added to Universal Animations when I get to it. I will make a note of this though.
