### ISSUE TITLE
Feature Request: DnD 3.3 and FVTT 12 compatibility

### ISSUE THREAD

**Issue by franckflo** [chrisk123999/chris-premades#275]
First and foremost: thank you for this wonderful module, it's greatly enhanced my DnD group's online experience and made my life much easier as a GM.

I'm not trying to nag you: I just saw that the last dependency for your module (DFreds Convenient Effects) just got updated to FVTT12 compatibility. That makes me wonder if your work on the compatibility for the latest DnD and FVTT version is making some headway.

Thanks!

**Comment by Autumn225** [comment]
There's much more information about the v12 version on the CPR discord, it's currently in public beta testing, manifest links are posted in the CPR discord server (or you could grab it from the dev branch here on github). Still in testing and only spells are completed for v12. DFCE and a bunch of other modules are no longer requirements.

**Comment by franckflo** [comment]
Got it, thanks for the info.
