### ISSUE TITLE
Focused Aim causes type error

### ISSUE THREAD

**Issue by Eligarf** [chrisk123999/chris-premades#28]
A monk with this feature missed the target, and the Focused Aim dialog popped up allowing the choice of how many ki points to spend. After selecting the correct amount of ki to correct the miss, I got the following error in the console log. Using CPR 0.2.8, midi 10.0.35, ddb-importer 3.4.12

focusedAim.js:36 Uncaught (in promise) TypeError: undefined. originItem.use is not a function
[Detected 2 packages: chris-premades, midi-qol]
    at Workflow.focusedAim (focusedAim.js:36:22)
    at async eval (eval at callMacro (workflow.js:1669:15), <anonymous>:4:3)
    at async Promise.all (index 0)
    at async Workflow.callMacros (workflow.js:1559:13)
    at async Workflow._next (workflow.js:440:6)
    at async Workflow.next (workflow.js:262:10)
    at async Item5e.doAttackRoll (itemhandling.js:517:2)
    at async Workflow._next (workflow.js:416:6)
    at async Workflow.next (workflow.js:262:10)
    at async Workflow.next (workflow.js:262:10)
    at async Workflow.next (workflow.js:262:10)
    at async Workflow.next (workflow.js:262:10)
    at async Workflow.next (workflow.js:262:10)

**Comment by chrisk123999** [comment]
I'll take a look at this when I get home later tonight.

**Comment by chrisk123999** [comment]
Could you screenshot the focused aim effect that is on the actor.  Specifically interested in seeing what it says the source is.

**Comment by Eligarf** [comment]
![image](https://user-images.githubusercontent.com/16523503/228713513-767e0b36-01da-401d-9d6e-b276d36e8399.png)

I've verified that the item referenced is Focused Aim using developer mode.

{
    "name": "Focused Aim",
    "type": "feat",
    "system": {
        "description": {
            "value": "When you miss with an attack roll, you can spend 1-3 ki points to increase your attack roll by 2 for each of these ki points you spend, potentially turning the miss into a hit.\n<details>\n  <summary>\n    More Details\n  </summary>\n  <p>\n    </p><p><em>5th-level monk feature</em><br />When you miss with an attack roll, you can spend 1 to 3 ki points to increase your attack roll by 2 for each of these ki points you spend, potentially turning the miss into a hit.</p>\n  <p></p>\n</details>",
            "chat": "",
            "unidentified": ""
        },
        "source": "",
        "activation": {
            "type": "special",
            "cost": 1,
            "condition": ""
        },
        "duration": {
            "value": "",
            "units": ""
        },
        "target": {
            "value": null,
            "width": null,
            "units": "",
            "type": ""
        },
        "range": {
            "value": null,
            "long": null,
            "units": ""
        },
        "uses": {
            "value": null,
            "max": "",
            "per": "",
            "recovery": ""
        },
        "consume": {
            "type": "charges",
            "target": "hobuo2x8EpPJuBzY",
            "amount": 1
        },
        "ability": "",
        "actionType": "other",
        "attackBonus": "",
        "chatFlavor": "",
        "critical": {
            "threshold": null,
            "damage": ""
        },
        "damage": {
            "parts": [],
            "versatile": ""
        },
        "formula": "",
        "save": {
            "ability": "",
            "dc": null,
            "scaling": "spell"
        },
        "type": {
            "value": "class",
            "subtype": ""
        },
        "requirements": "",
        "recharge": {
            "value": null,
            "charged": false
        }
    },
    "flags": {
        "ddbimporter": {
            "id": "2438003",
            "entityTypeId": "222216831",
            "componentId": 3035408,
            "componentTypeId": 12168134,
            "type": "class",
            "class": "Monk",
            "subclass": "Way of Shadow",
            "dndbeyond": {},
            "effectsApplied": true,
            "chrisEffectsApplied": true,
            "chrisPreEffectName": "Focused Aim",
            "importId": "NDBFjgrEfx2WUPAF"
        },
        "infusions": {
            "infused": false
        },
        "obsidian": {
            "source": {
                "type": "class",
                "text": "Monk"
            }
        },
        "midi-qol": {
            "onUseMacroName": "",
            "effectActivation": false
        },
        "custom-character-sheet-sections": {
            "sectionName": ""
        },
        "rest-recovery": {
            "data": {
                "recovery": {
                    "enabled": false
                }
            }
        },
        "midiProperties": {
            "nodam": false,
            "fulldam": false,
            "halfdam": false,
            "rollOther": false,
            "critOther": false,
            "magicdam": false,
            "magiceffect": false,
            "concentration": false,
            "toggleEffect": false,
            "ignoreTotalCover": false,
            "autoFailFriendly": false,
            "autoSaveFriendly": false,
            "offHandWeapon": false
        },
        "magicitems": {
            "enabled": false,
            "equipped": false,
            "attuned": false,
            "charges": "0",
            "chargeType": "c1",
            "destroy": false,
            "destroyFlavorText": "reaches 0 charges: it crumbles into ashes and is destroyed.",
            "rechargeable": false,
            "recharge": "0",
            "rechargeType": "t1",
            "rechargeUnit": "r1",
            "sorting": "l"
        },
        "exportSource": {
            "world": "homebrew",
            "system": "dnd5e",
            "coreVersion": "10.291",
            "systemVersion": "2.1.4"
        }
    },
    "effects": [
        {
            "label": "Focused Aim",
            "icon": "icons/skills/targeting/target-strike-triple-blue.webp",
            "changes": [
                {
                    "key": "flags.midi-qol.onUseMacroName",
                    "mode": 0,
                    "value": "function.await chrisPremades.macros.focusedAim,preCheckHits",
                    "priority": 20
                }
            ],
            "transfer": true,
            "_id": "rzksUWAkBsCf1Eie",
            "disabled": false,
            "duration": {
                "startTime": null,
                "seconds": null,
                "combat": null,
                "rounds": null,
                "turns": null,
                "startRound": null,
                "startTurn": null
            },
            "origin": null,
            "tint": null,
            "flags": {
                "dae": {
                    "selfTarget": false,
                    "selfTargetAlways": false,
                    "stackable": "none",
                    "durationExpression": "",
                    "macroRepeat": "none",
                    "specialDuration": []
                },
                "core": {
                    "statusId": ""
                },
                "ActiveAuras": {
                    "isAura": false,
                    "aura": "None",
                    "radius": "null",
                    "alignment": "",
                    "type": "",
                    "ignoreSelf": false,
                    "height": false,
                    "hidden": false,
                    "displayTemp": false,
                    "hostile": false,
                    "onlyOnce": false
                },
                "dfreds-convenient-effects": {
                    "description": ""
                }
            }
        }
    ],
    "_id": "NKmtLsToLZvA6fTZ",
    "img": "icons/skills/targeting/target-strike-triple-blue.webp",
    "folder": null,
    "sort": 700000,
    "ownership": {
        "default": 0,
        "imLxB9KPmJBqVcY5": 3
    },
    "_stats": {
        "systemId": "dnd5e",
        "systemVersion": "2.1.5",
        "coreVersion": "10.291",
        "createdTime": 1680143594764,
        "modifiedTime": 1680143596001,
        "lastModifiedBy": "imLxB9KPmJBqVcY5"
    }
}

**Comment by Eligarf** [comment]
perhaps an await missing on line 35 at the fromUuid?

**Comment by chrisk123999** [comment]
Try the latest update.  I did the fix from mobile so I haven't tested it.  The missing await seems right.

**Comment by Eligarf** [comment]
All good now.
