### ISSUE TITLE
Warpgate requirement?

### ISSUE THREAD

**Issue by InconspicuousBear** [chrisk123999/chris-premades#283]
Why does it list Warpgate as requirement? The Module is dead. Or is there something else?

**Comment by Sayshal** [comment]
Warpgate is only a requirement for V11 CPR which warpgate still functions in.

**Comment by Sayshal** [comment]
@InconspicuousBear did you get a resolution? If not I recommend joining the discord for better support.

**Comment by InconspicuousBear** [comment]
All is good, I am glad I have to use one module less!
