### ISSUE TITLE
[Bug] Wither and Bloom does nothing

### ISSUE THREAD

**Issue by NickRimer03** [chrisk123999/chris-premades#286]
Current version of this spells does really nothing. It looks like its automation is broken.

You may place measure template and watch a beautiful animation but no dice will be rolled, and no damage dealt. Also, this spell may heal 1 friend, but there is no healing inside this spell.

I don't know well is it possible to choose which targets inside the template must be damaged or healed but it can be a good option.

DAE, MidiQoL, Chris Premades 0.12.57

**Comment by chrisk123999** [comment]
Hi, please join the CPR Discord support channel for troubleshooting. As the spell should be functional.
