### ISSUE TITLE
Starry Form: Wise Dragon doesn't set minimums for saves

### ISSUE THREAD

**Issue by flyingsquad** [chrisk123999/chris-premades#289]
This is for the 0.12.63 release.

The Circle of Stars druid feature Starry Form: Wise Dragon is defined as:

**Dragon**. A constellation of a wise dragon appears on you. When you make an Intelligence or a Wisdom check or a Constitution saving throw to maintain concentration on a spell, you can treat a roll of 9 or lower on the d20 as a 10.

The active effects placed on the character when this is invoked only include the ATL lighting effects. Shouldn't it also set the minimum saving throws like this?

flags.midi-qol.min.ability.save.int = 10
flags.midi-qol.min.ability.save.wis = 10
flags.midi-qol.min.ability.save.concentration = 10

**Comment by Autumn225** [comment]
Those flags are already on the item. It's very likely that Midi doesn't give a visual indication of these flags working.
