### ISSUE TITLE
Performance issues while moving tokens

### ISSUE THREAD

**Issue by Bashewsruinedmylife** [chrisk123999/chris-premades#295]
ever since I installed the beta version for V12 there is a significant stuttering of the whole game when moving tokens. happens both when draggin or when moving via WASD but with WASD it is much worse. this issue scales in intensity as more tokens are moved simultaneously. I also tested running the same core V and system V with all other modules being the same and simply turning off CPR solves the issue outright. is this a common/known issue and if so: is there a solution/workaround?

as always many thanks in advance, love the module, you guys are doign fantastic work!

**Comment by chrisk123999** [comment]
Performance with token movement is something that's being looked into.
What cover module do you have (if any) and how many tokens and walls are on the scene you're on?

**Comment by Bashewsruinedmylife** [comment]
currently using simbuls cover calculator / simbuls athenaeum.
about the walls and tokens: it depends, though performance did improve on one map with only a few tokens and comparatively few walls as well. it was a 22x16 squares map with 12 tokens in total and about 40-50 walls

**Comment by chrisk123999** [comment]
The latest version has an option that may help with this. Try using the Movement Performance setting and see if any of the modes help.

**Comment by Bashewsruinedmylife** [comment]
I just updatet to 0.12.77. and tried all three settings and unfortunately I can't say I'm noticing any difference :( even on low the stuttering is pretty much exactly the same

if theres anything else I could try or provide to help, just shoot

**Comment by Bashewsruinedmylife** [comment]
update: deactivating simbuls cover calculator + athenaeum fixed a great deal of the issue! moving multiple tokens at once is still a little bit non-fluent/clunky, but I am guessing that is a broader performance issue with foundry and detached from CPR

**Comment by Hazuma81** [comment]
Hi , I've encountered the same problem regarding single and multiple token movement , I don't have any module that determines the covers but when I move the tokens, before they reach their destination, they freeze for a moment.
By disabling CPR the problem is not there, if I leave CPR and its dependencies active and disable everything else the problem returns

**Comment by Dr-Feargood** [comment]
I had been having this problem myself for a while, so I changed performance to low in core performance mode, it didn't help me, or is Movement Performance setting something else I can't find?

**Comment by chrisk123999** [comment]
> I had been having this problem myself for a while, so I changed performance to low in core performance mode, it didn't help me, or is Movement Performance setting something else I can't find?

This issue has long since been resolved. Make sure your CPR is up to date. If you have Monk's Wall Enhancement disable the one way doors setting.
