### ISSUE TITLE
Shocking Grasp not working

### ISSUE THREAD

**Issue by ravingdragoon** [chrisk123999/chris-premades#3]
When I try to cast Shocking Grasp the flow works as expected for attack and damage, but there is no additional effect. I get the following error when I attempt to use the spell and when I attempt to run the macro manually.

```
Uncaught (in promise) ReferenceError: undefined. chrisPremades is not defined
[Detected 1 package: itemacro]
    at eval (eval at Item._executeScript (helper.js:82:18), <anonymous>:4:9)
    at Macro.eval (eval at Item._executeScript (helper.js:82:18), <anonymous>:5:9)
    at Item._executeScript (helper.js:88:12)
    at Item.executeMacro (helper.js:60:23)
    at ItemMacroConfig._onExecute (ItemMacroConfig.js:43:10)
 		 | eval | @ | VM477210:5
 		 | Item._executeScript | @ | helper.js:88
 		 | Item.executeMacro | @ | helper.js:60
 		 | _onExecute | @ | ItemMacroConfig.js:43
 		 | await in _onExecute (async) |   |  
 		 | dispatch | @ | jquery.min.js:2
 		 | y.handle | @ | jquery.min.js:2
```

**Comment by chrisk123999** [comment]
Can you double check that your Item Macros module has every setting for it turned off?

**Comment by ravingdragoon** [comment]
They are all off. I don't even see any of the macros from your module in my compendiums. Perhaps because I use The Forge for hosting it is not seeing the Macros folder properly?

**Comment by chrisk123999** [comment]
Fixed in latest release.  Was a file structure on Linux systems bug.
