### ISSUE TITLE
[bug] Channel Divinity: Turn undead is not auto targeting nearby valid creatures

### ISSUE THREAD

**Issue by Orionox** [chrisk123999/chris-premades#30]
Basically, exactly as the title says. I imported channel divinity, placed it on a character and cast it while surrounded by ghouls. None of the ghouls were targeted. If I target the ghouls ahead of time it works though, and the channel divinity is applied to them

**Comment by chrisk123999** [comment]
Could you screenshot the details tab of the item for me?

**Comment by Orionox** [comment]
![Screenshot 2023-03-30 170709](https://user-images.githubusercontent.com/20059838/228984088-b155c035-0f5d-4478-b4f8-75d3f35b7677.jpg)

**Comment by chrisk123999** [comment]
What version of midi-qol and my module are you on?  And is there any errors in console?

**Comment by Orionox** [comment]
Most updated on both, I just ran the updater. 
![Screenshot 2023-03-30 171526](https://user-images.githubusercontent.com/20059838/228985322-5e63e1a6-d31e-41c7-914e-5161a9b90843.jpg)

**Comment by Orionox** [comment]
oops that is slightly wrong, I was manually targeting the ghoul

**Comment by chrisk123999** [comment]
Are you using this on a levels map or have a wall between the target(s) and actor?

**Comment by Orionox** [comment]
no walls, I do have levels as a module, but its not active on the scene im using to test

**Comment by chrisk123999** [comment]
![image](https://user-images.githubusercontent.com/2249355/228985874-f783c557-cda2-4c1a-b0eb-4277a8c89b98.png)
Could you make sure this isn't set to none?

**Comment by Orionox** [comment]
That was set to none, lol. its always something so small.
