### ISSUE TITLE
Fey Ancestry and Charmed

### ISSUE THREAD

**Issue by gurgugnao** [chrisk123999/chris-premades#31]
Hello Chris,

First of all, fantastic work!
I noticed that Fey Ancestry advantage against Charmed condition applies only for Charm Person spell (probably related to its macro and its effect) instead of any item that has an effect that apply the Status Effect Charmed (CE) or, directly, an effect of Charmed from CE.

Example of Charm Person spell that with this two effects does not trigger advantage from Fey Ancestry.
![Charmed (1)](https://user-images.githubusercontent.com/122090327/229375402-64ede2b1-c5d4-46a1-9dc8-c818ca0b23c4.JPG)

Also, Charm Person spell applies 2 effects to the token that fails the save: 1) Charm Person effect with a minute duration and 2) Charmed condition effect with unlimited duration.
![Charmed (2)](https://user-images.githubusercontent.com/122090327/229375404-289e0880-33f8-44f4-8ba4-412e5a17aefc.JPG)

Can you review it?

Thank you!

**Comment by MotoMoto1234** [comment]
Pretty sure all of his automation around conditions rely on all your items and spells using the `macro.ce` key.

**Comment by chrisk123999** [comment]
@MotoMoto1234 Is correct, you must be using `macro.ce` for it to apply.

**Comment by MotoMoto1234** [comment]
Also, there is the glitch the first time you login to a server, you wil see duplicate effects, however in your case the two icons are standard, if the macro.ce charm person effect is removed the charmed condition follows suit, almost like concentration in midi.  The glitch duplicate effects is clientside only and is superficial.

**Comment by gurgugnao** [comment]
Ok, thanks for the answers. If I understood correctly, it is not possible right now to modify the items to avoid the double effect and apply only the condition from CE.
Just a curiosity: why the CE condition applied with macro.ce does not have the description and its duration is unlimited?

**Comment by chrisk123999** [comment]
`macro.ce` handles removing the condition when the effect that created it is removed.
