### ISSUE TITLE
Squire of Solamnia: Precise Strike - extra damage not applied

### ISSUE THREAD

**Issue by wheeeels** [chrisk123999/chris-premades#310]
I'm trying out Squire of Solamnia: Precise Strike and it seems the extra damage is not being applied. 

- Applied advantage works
- Recovery of use if attack misses works.

![image](https://github.com/user-attachments/assets/e9c567ff-5a55-4ab2-94aa-0226048f27a3)

On an extra note, it does not show any icon applied to the char, indicating Squire of Solamnia: Precise Strike has been activated. Not sure this is intended or not.

![image](https://github.com/user-attachments/assets/9bf881be-ba2a-42ad-a610-10a35b8c7a86)

**Comment by chrisk123999** [comment]
That automation isn't from CPR. It's likely from Midi Item Showcase or DDBI.

**Comment by wheeeels** [comment]
you are right. apologies. i probably checked the wrong feat and didnt notice
