### ISSUE TITLE
[BUG] Error messages in skill roll messages when multiple rolls are made by different players at the same time.

### ISSUE THREAD

**Issue by joaquinpereyra98** [chrisk123999/chris-premades#327]
**Foundry**
- Foundry v12.331

**System**:
- DnD5e v3.3.1

> The world has been created for the purpose of replicating the bug.

**Modules Installed**:

1. Cauldron of Plentiful Resources - 1.0.39
2. ​Dynamic effects using Active Effects (DAE) - 11.3.65
3. libWrapper - 1.13.2.0
4. ​Midi QOL - 11.6.25.1
5. ​Sequencer - 3.4.3
6. socketlib - 1.1.0
7. Times Up - 11.3.19

**How to replicate it**

Execute a macro script with the following code:
```js
const actor= await fromUuid("uuid of a actor1");
const actor2 = await fromUuid("uuid of actor 2");
actor.rollSkill("ath")
actor2.rollSkill("ath")
```
![img-2024-11-05-21-03-37](https://github.com/user-attachments/assets/ba046ecd-77d7-44b9-9f49-b46ed4c5c746)

**Note**:
if a timeout of one millisecond is added between rolls, the bug does not occur.
```js
const actor= await fromUuid("uuid of a actor1");
const actor2 = await fromUuid("uuid of actor 2");
actor.rollSkill("ath")
await new Promise(r => setTimeout(r, 1));
actor2.rollSkill("ath")
```
![imagen](https://github.com/user-attachments/assets/c2b60a49-c3a8-4dde-a177-928aca4eb8a8)

**Comment by Autumn225** [comment]
Sorry, what part does CPR play in this? You didn't include any details of how this is CPR related.

**Comment by chrisk123999** [comment]
I'd there a console error?

**Comment by joaquinpereyra98** [comment]
> Sorry, what part does CPR play in this? You didn't include any details of how this is CPR related. And is rollSkill an async function?
the bug only happens if CPR is activated in the world
rollSkill  is async

**Comment by chrisk123999** [comment]
What's the bug?

**Comment by Autumn225** [comment]
And what happens if you await the roll skill?

**Comment by joaquinpereyra98** [comment]
> Is there a console error?

there is no error in the console

> What's the bug?

When skill rolls are made for different actors in the chat they appear as if they belong to the same actor.
**Note**: the modifiers seem to be correct, the error is only at the moment of creating the message.

>And what happens if you await the roll skill?

the bug does not appear

**Comment by Autumn225** [comment]
I don't think it counts as a bug if you're using a function not as intended. If it works fine when it's properly awaited, I see no issue. Yes it's probably caused by the extra millisecond of code it goes through when CPR patches the function, but I don't think there's anything CPR can do about that.

**Comment by roth-michael** [comment]
(I do still plan to look into it, in case for whatever reason those rolls are forced to happen in a sync context - though I do think not awaiting them is likely to result in unexpected behavior)

**Comment by roth-michael** [comment]
Will wait to close until the next release is out and you can verify it works with your code, but feeling confident that I squashed it.
