### ISSUE TITLE
Vampiric Touch Attack as a spell and not a feat?

### ISSUE THREAD

**Issue by ctbritt** [chrisk123999/chris-premades#34]
Is it possible to change VTA to a necro spell instead of a feat, please? Taking Grim Harvest into account and I'm trying to automate that.

**Comment by chrisk123999** [comment]
I didn't change it to a spell, but I did add the cast data to the item flags in the next release.  I also went ahead and made the Grim Harvest class feature while I was at it.

**Comment by chrisk123999** [comment]
For reference, the cast data flags are located at: `flags.chris-premades.spell.castData`

**Comment by ctbritt** [comment]
you are a prince. i've been working off Kandashi's old 5e-wizard automation module.
