### ISSUE TITLE
Module Conflict with Items with Spells

### ISSUE THREAD

**Issue by MotoMoto1234** [chrisk123999/chris-premades#37]
When you try to update an Items with Spells Spell with the medkit/chest button on the top bar, the spell is removed and then added to the generic spell categories and the items with spells Item is detached and spell less.  

![image](https://user-images.githubusercontent.com/116308065/230724292-d5cbc424-4514-4787-92da-b3b9003778a6.png)

**Comment by LukasPrism** [comment]
Came here to ask this. We’re using IWS a lot and unfortunately yeah the medkit breaks stuff. It does take several steps to get equipment updated with the latest versions of CPR spells, especially when the spell uses a certain number of charges. I’m not sure there’s going to be a way around that

**Comment by MotoMoto1234** [comment]
My table has a long standing golden rule, do not medkit IWS items or spells.

**Comment by LukasPrism** [comment]
I’ve *just* given them medkit access last session, which paid off when the cleric suddenly took Spiritual Weapon. So we’ll need to go over this rule ASAP

**Comment by chrisk123999** [comment]
Items with spells is unlikely to be updated so I'm going to close this issue.
