### ISSUE TITLE
Use premades for not yet done abilities and homebrew

### ISSUE THREAD

**Issue by jtgeraldes** [chrisk123999/chris-premades#39]
I've started using the module this month and the quality is amazing! 

I noticed that some automations have hard coded scripts in the module directory that are hard to duplicate and apply to other abilities, with minor changes. For instance - Aura of Devotion could be easily use the prep from Aura of Courage (just the condition effect is different) or Turn the Unholy can be written using Turn Undead. Is there an easy way for us to make this customisations without breaking the module presets?

ps.: tks for the module!

**Comment by chrisk123999** [comment]
Most macros from my module can be copied into an item macro and work with the following changes:
Replace `chris` with `chrisPremades.helpers`
Replace `queue` with `chrisPremades.queue`

If there is an effect aura involved, it's slightly more complicated, but still possible.
