### ISSUE TITLE
Translatable or not?

### ISSUE THREAD

**Issue by Padhiver** [chrisk123999/chris-premades#4]
Hello' !
Thanks for all the automation, it's really great. 😄 

I was wondering, playing in another language, I just need to replace the descriptions and title, and that's it, but some scripts probably use the spell or ability name in their codes, would it be possible to know which ones?

I try to look in the scripts myself, but not being a dev it's not easy. 

Thanks in any case!

**Comment by chrisk123999** [comment]
As it stands the only current features that use item names in the macros are:

- Blade Flourish
- Vampiric Touch
- Experimental Elixir

Translating isn't something I really thought about, and I'll need to figure out a more creative way to avoid using item names in code.

**Comment by Padhiver** [comment]
Okay, thanks!
There are very few of them actually. :)

For the translation it's not really a problem, just copying and pasting the descriptions doesn't really take long.
Sorry to have created an issue anyway, I think you can close it, it's not really a bug. :D

**Comment by chrisk123999** [comment]
Upon thinking about it, avoid renaming any effect names for anything that uses an Item Macro.

**Comment by chrisk123999** [comment]
The next update will notate in the description if it's safe to be renamed.

**Comment by Padhiver** [comment]
Oh cool, thank you. :) sorry for the extra work!
