### ISSUE TITLE
Ring of Spell Storing

### ISSUE THREAD

**Issue by Pantherdad** [chrisk123999/chris-premades#41]
I'm using your Ring of Spell Storing. Most spells are working well from it. but not some of the ones that you apply to yourself, like Mirror Image, Mage Armor or Blur. They expend the use in the ring when you try to use it, but the spell doesn't cast and have an effect. I don't know if I am doing something wrong, or if there is a fix for this.

**Comment by chrisk123999** [comment]
I'm having trouble reproducing this issue.  It may be a case of different Midi-Qol settings getting in the way.

**Comment by chrisk123999** [comment]
The spells weren't working due to using continent effects name matching.
