### ISSUE TITLE
Incompability with Dice so Nice

### ISSUE THREAD

**Issue by aronjanosch** [chrisk123999/chris-premades#42]
The rolls from dice so nice still seem to be incompatible.
**For hex:**
1. Only one roll get displayed (the damage roll from the weapon, not the hex damage roll)
2. The Number on the dice displayed do not match the values rolled in the formula (seen in chat) for neither roll (weapon damage and hex damage)
**For Toll of the Dead**
When the target is full health -> everything works: correct die, correct value
When the target has lost hp -> formula works, full hp die is displayed, with incorrect value.

It seems the macros don't trigger the right die from dice so nice.

**Comment by chrisk123999** [comment]
This needs to be fixed on Midi-Qol's side.  The dice so nice roll needs to be moved after the postDamageRoll step of the workflow.
