### ISSUE TITLE
Lightning Arrow and Planar Warrior

### ISSUE THREAD

**Issue by MythicalRollers** [chrisk123999/chris-premades#43]
This is going to be a weird one I am sure.  Mr.Primate has a macro effect for Planar Warrior but it and your Lightning Arrow conflict.  Planar Warrior should convert all damage type to Force, but with your Lightning Arrow, only the additional damage from Planar Warrior is Force. The rest is Lightning.  All required modules up to date as of 4/18/2023.
![image](https://user-images.githubusercontent.com/106455111/233187131-efa78c12-f175-49b2-b738-36d1806768c3.png)

**Comment by chrisk123999** [comment]
Not much I can do about this other than make my own Planer Warrior automation that uses my queue system change damage types.

**Comment by MythicalRollers** [comment]
Can I request such a magical feature? (Big sad doggy eyes)
