### ISSUE TITLE
Summon Token Reverts after being Placed

### ISSUE THREAD

**Issue by KellethDregar** [chrisk123999/chris-premades#44]
Not sure if this is due to configuration but for some reason the summon token seems to revert back to the default image once the token is actually placed. 

![image](https://user-images.githubusercontent.com/79947702/233429525-5fc45863-d395-4bff-9ea3-8cdd97b0b6e0.png)
![image](https://user-images.githubusercontent.com/79947702/233429579-48436017-eb6b-4ecc-8093-75fc599dc593.png)
![image](https://user-images.githubusercontent.com/79947702/233429615-2e6b4320-e11a-42eb-92f3-dd40a77d2a30.png)

Avatar Image remains though

![image](https://user-images.githubusercontent.com/79947702/233430307-a16bcd44-d82e-46ef-b258-8edcd6ab52d8.png)

The token Image is set to default 
![image](https://user-images.githubusercontent.com/79947702/233430626-a3b0f03b-f76b-4b2d-9036-e9bf05a53801.png)

**Comment by chrisk123999** [comment]
Does this happen with all summons or just this one?  Have you tried with only my module and it dependencies enabled?

**Comment by KellethDregar** [comment]
Ah sorry about that. Found a conflict with another module that has a feature that can interact with token art. The feature was toggled to disabled but seems like it still affects the token art somehow. Removed the module for now and it works just fine, will notify them of the interaction to see if they can take a look.
