### ISSUE TITLE
[bug] Patient Defense no duration

### ISSUE THREAD

**Issue by V3rotti** [chrisk123999/chris-premades#46]
The is no duration in the effect for Patient Defense. I changed the duration manually to make it work as expected:
![image](https://user-images.githubusercontent.com/56869989/233986556-435e1989-ca65-4885-ae21-ec6842909473.png)

**Comment by MotoMoto1234** [comment]
Can confirm the issue but just 1 round isn't really enough to cover all scenarios.  Should be 7-12 seconds, 1 round and 1 turn, and the special duration you chose.

**Comment by chrisk123999** [comment]
I'll get this fixed in the next update.
