### ISSUE TITLE
Unable to get Summon Fiend to Work

### ISSUE THREAD

**Issue by KellethDregar** [chrisk123999/chris-premades#47]
Set it up similarly to the other Summon spells but "Summon Fiend" seems to add concentration but not prompt for selection of Devil, Demon or Yugoloth.

Couldn't find any relevant errors in the console and it still occurs when only enabling required modules.

**Comment by chrisk123999** [comment]
Looks like I actually forgot to include the spell in the compendium.  You likely just have the DDB importer version.  I'll be fixed next update.

**Comment by KellethDregar** [comment]
Ah ok checks out, yeah noticed it wasn't in the spells compendium. Thanks!

**Comment by chrisk123999** [comment]
Try the version I just released.
