### ISSUE TITLE
CPR Character Sheet Button Missing

### ISSUE THREAD

**Issue by ravingdragoon** [chrisk123999/chris-premades#48]
Since updating from Chris's Premades 0.3.1 to 0.3.3 the Character Sheet button to apply Chris's Premades to a character has disappeared.

**Comment by chrisk123999** [comment]
Do you have the DDB importer enabled?  It requires that.

**Comment by ravingdragoon** [comment]
I do have it enabled, yes.

**Comment by ravingdragoon** [comment]
It seems to have randomly returned on a reload. I will let you know if it happens again.
