### ISSUE TITLE
Elemental Adept not applying

### ISSUE THREAD

**Issue by Dyrnwyrm** [chrisk123999/chris-premades#52]
Im was doing a session as i started noticing that the damage from elemental adept (ignore resistance) was not applying at all, i tried on an NPC sheet and on a Blank Sheet (no class, no items only elemental adept + firebolt from SRD compendium) and the issue persists.

10.0.28 DAE
10.0.41 Midi
0.3.41 CPR

![image](https://user-images.githubusercontent.com/129613553/236660476-135e2704-1cfd-44b9-bcdd-bdf6f5e89ccb.png)

**Comment by chrisk123999** [comment]
Your damage formula has min 2 in it.  Make sure the elemental adept setting is also on.
