### ISSUE TITLE
Bug: incorrect duration on summon undead ghostly - deathly touch

### ISSUE THREAD

**Issue by KammaKhazi** [chrisk123999/chris-premades#54]
Hi, I've just been doing some pregame testing of your tasha's summon undead implemention. First up, absolutely amazing work thankyou!

I did notice that I think the duration on the ghostly undead's deathly touch is incorrect. Frightened should be remove at end of target's next turn, it seemed to stick around until the start of the target's turn the turn after that one.

**Comment by chrisk123999** [comment]
Fixed in the next release.

**Comment by KammaKhazi** [comment]
Cheers for the quick upload. I have just tested this however, the frightened DAE effect generated now has no duration or special expiry conditions set, so it just comes as unlimited.

**Comment by chrisk123999** [comment]
That effect will go away one it's own when the other effect is removed.  It's applied via a `macro.ce` flag.
