### ISSUE TITLE
Hunter's marks not damage

### ISSUE THREAD

**Issue by rinnocenti** [chrisk123999/chris-premades#56]
he applies the effects correctly, but when it comes to generating the damage bonus he doesn't. 

[playertest.zip](https://github.com/chrisk123999/chris-premades/files/11534604/playertest.zip)

DAE:10.0.30
MIDI:10.0.43
Cris: 0.3.56

**Comment by chrisk123999** [comment]
Could you screenshot your chat card after making an attack on the target?

**Comment by rinnocenti** [comment]
![image](https://github.com/chrisk123999/chris-premades/assets/3178127/7f591497-0742-44c0-87d3-0568929dbc93)

**Comment by chrisk123999** [comment]
Could you join my Discord?  I'll be able to troubleshoot it better there.  The link to it is on the main GitHub page.

**Comment by rinnocenti** [comment]
I'm going to open it again because now it gives me another error.
(even updating to this latest version 0.3.58)
![image](https://github.com/chrisk123999/chris-premades/assets/3178127/4df43721-5131-4b26-9b2a-6cd08daeedc4)

**Comment by chrisk123999** [comment]
Fixed in the latest release.
