### ISSUE TITLE
Receiving an error: "net::ERR_ABORTED 404 (Not Found) on load" with regards to Danse Macabre

### ISSUE THREAD

**Issue by rjbprime** [chrisk123999/chris-premades#59]
Hey mate,

Upon load of Foundry, I am getting the following error:

```js

GET http://localhost:31216/modules/chris-premades/scripts/macros/spells/danseMacabre.js net::ERR_ABORTED 404 (Not Found)

```

I've tried going through a clone of the github, to see if it has been deleted/moved/misplaced, and I can't seem to find it. Can this be looked at?

Kind regards.

**Comment by chrisk123999** [comment]
Sorry about that, I forgot I had a reference to this WIP automation when I updated the main macros file.  Should be fixed now.
