### ISSUE TITLE
Elemental Adept not turning 1's to 2's

### ISSUE THREAD

**Issue by RexxDM** [chrisk123999/chris-premades#60]
![image](https://github.com/chrisk123999/chris-premades/assets/134309842/028eb0e1-8cd5-426d-834b-7a6c73e259a2)

Seems like the Elemental Adept stopped turning 1s to 2s. That "strange" formula around the Fireball Damage goes away if I disable the Elemental Adept feature. It does ignore resistances correctly tho.

**Comment by chrisk123999** [comment]
I just realized that formula won't work like I thought it would.  I'll get this corrected.
