### ISSUE TITLE
Heated Body

### ISSUE THREAD

**Issue by MotoMoto1234** [chrisk123999/chris-premades#61]
The Heated body feature, atleast for the Azer, targets the Azer instead of the attacker.  

![image](https://github.com/chrisk123999/chris-premades/assets/116308065/cc94dca7-f265-4cc2-8c5d-d589b3a3555d)

**Comment by pospa4** [comment]
![image](https://github.com/chrisk123999/chris-premades/assets/135047480/834e5021-57c6-4aaa-991c-bf87b3909bc7)
Same thing with salamander ( i cancelled salamander's fire immunity thats why it takes dmg)
