### ISSUE TITLE
[Suggestion] Blink's "blink away" adds Convenient Effects 'Invisible' condition.

### ISSUE THREAD

**Issue by Janner3D** [chrisk123999/chris-premades#67]
It would be nice if there was an option to add the 'invisible' condition to the Blink Away effect on the Blink Spell so the token would truly be invisible to other players, instead of altering the opacity.

**Comment by MotoMoto1234** [comment]
It wouldn't be rules as written, as the creature would be seeable by people with seeall detection modes.  The only people who can see blinked creatures are people who can see into the ethereal plane.

**Comment by chrisk123999** [comment]
Currently it just places an effect on them that prevents them from being easily targeted.  I'll see what else I can do.

**Comment by MotoMoto1234** [comment]
I wonder if the new detections modes module by dev# could make this easier to handle.

**Comment by chrisk123999** [comment]
I added support for vision 5e.
