### ISSUE TITLE
Detect Thoughts

### ISSUE THREAD

**Issue by MythicalRollers** [chrisk123999/chris-premades#7]
After casting this spell a new feature called "Detect Thoughts - Probe Deeper" will be available on your features.
(No feature is added, no errors in console either.)
If you use "Tidy 5e Sheet" it will automatically be favorited.
(I use Tidy 5e Sheet, and if the feature was added and I missed it, it should have still been favorited, but it wasn't.)
I have made no changes to your spell item.  I have only added it to a test character.
Foundry: 10.291
dnd5e: 2.1.5
Chris's: 0.0.22
All other modules up to date as of yesterday at 11PM CST.

**Comment by chrisk123999** [comment]
Fixed in the release I just put out.  I forgot to include "ItemMacro" in the midi-qol on use field.
