### ISSUE TITLE
Module has vanished on v10

### ISSUE THREAD

**Issue by Quinn-Aetherwood** [chrisk123999/chris-premades#76]
I haven't upgraded to 11 yet, but your module has vanished from modlist. I can't see it as a mod to enable even though i have your module installed.

**Comment by chrisk123999** [comment]
What is your DND system version?

**Comment by Quinn-Aetherwood** [comment]
My God you're quick. I haven't updated my dnd 5e version. I actually started doing that. I think that is probably the issue i am assuming.

**Comment by chrisk123999** [comment]
Yep.  Update to 2.2.1.

**Comment by Quinn-Aetherwood** [comment]
yeah that  was it. Just going to take this opportunity to say how bad ass your module is. It is one of my faves
