### ISSUE TITLE
Darkenss not follow the caster

### ISSUE THREAD

**Issue by gioppoluca** [chrisk123999/chris-premades#77]
I understood that it was possible to place the darkness spell on a target token and the aura would have moved with the token but it seems that is not.
Am I doing something wrong or this is not an existing feature?

**Comment by gioppoluca** [comment]
BTW I'm on V11

**Comment by chrisk123999** [comment]
You should have been prompted to attach it or not.  Make sure you have token attacher enabled.

**Comment by gioppoluca** [comment]
No prompt and it is enabled.
Here is the log:
```
Foundry VTT | Retrieved and compiled template systems/dnd5e/templates/actors/character-sheet.hbs
commons.js:2004 Error: You are accessing the Actor5e#data object which is no longer used. Since V10 the Document class and its contained DataModel are merged into a combined data structure. You should now reference keys which were previously contained within the data object directly.
    at logCompatibilityWarning (commons.js:1993:19)
    at Actor5e._logV10CompatibilityWarning (commons.js:8440:14)
    at get data [as data] (commons.js:8328:24)
    at WindowMenu.winIcon (windowMenu.js:57:24)
    at WindowMenu.newWindow (windowMenu.js:30:34)
    at WindowMenu.windowAdded (windowMenu.js:66:31)
    at #call (foundry.js:730:20)
    at Hooks.call (foundry.js:712:38)
    at Object.newWindowRendered [as fn] (windowManager.js:89:15)
    at #call (foundry.js:730:20)
    at Hooks.callAll (foundry.js:687:17)
    at ActorSheet5eCharacter._render (foundry.js:5813:13)
    at async ActorSheet5eCharacter._render (foundry.js:6488:5)
logCompatibilityWarning @ commons.js:2004
foundry.js:7620 Foundry VTT | Retrieved and compiled template systems/dnd5e/templates/apps/ability-use.hbs
foundry.js:5760 Foundry VTT | Rendering AbilityUseDialog
commons.js:8703 Foundry VTT | Created ChatMessage with id [NNhlWQH1xMABGccD]
commons.js:2004 Error: You are accessing the Item5e#data object which is no longer used. Since V10 the Document class and its contained DataModel are merged into a combined data structure. You should now reference keys which were previously contained within the data object directly.
    at logCompatibilityWarning (commons.js:1993:19)
    at Item5e._logV10CompatibilityWarning (commons.js:8440:14)
    at get data [as data] (commons.js:8328:24)
    at AbilityTemplate.fromItem (terrain-main.js:557:23)
    at 🎁call_wrapper [as call_wrapper] (libWrapper-wrapper.js:616:16)
    at 🎁game.dnd5e.canvas.AbilityTemplate.fromItem#0 (libWrapper-wrapper.js:189:20)
    at Item5e.use (item.mjs:869:57)
    at async Item5e.doItemUse (itemhandling.js:305:15)
logCompatibilityWarning @ commons.js:2004
2token-attacher.js:1097 Token Attacher | Tools added.
commons.js:8703 Foundry VTT | Created MeasuredTemplate with id [LiBYpFaRXLUzE6cZ] in parent Scene [GTnI5KvGZ5rBQiv7]
DevTools failed to load source map: Could not load content for chrome-extension://mbopgmdnpcbohhpnfglgohlbhfongabi/dist/browser-polyfill.min.js.map: System error: net::ERR_BLOCKED_BY_CLIENT
```

**Comment by chrisk123999** [comment]
Could you open console and type `chrisPremades.troubleshoot()` and paste / send the generated file.

**Comment by gioppoluca** [comment]
/////////////// Game Information ///////////////
Foundry: 11.301
System: 2.2.1
Chris's Premades: 0.4.19

/////////////// Required Modules ///////////////
Automated Animations: 4.2.53
Build A Bonus: 11.0.2
Compendium Folders: 2.6.1
Dynamic Active Effects: 10.0.34.1
DFreds Convenient Effects: 5.0.1
Effect Macro: 11.0.0
Item Macro: 1.8.0
libWrapper: 1.12.12.1
Midi-Qol: 10.0.48.3
Sequencer: 3.0.10
Socketlib: 1.0.13
Template Macro: 11.0.0
Token Attacher: v4.5.13
Warpgate: 1.17.2

/////////////// Optional Modules ///////////////
About Time: Missing!
Advanced Token Effects: Missing!
Custom Character Sheet Sections: Missing!
D&D Beyond Importer: Missing!
Simple Calendar: Missing!
FXMaster: Missing!
Jules&Ben's Animated Assets (P): 0.5.8 (Disabled)
Jules&Ben's Animated Assets (F): Missing!
Quick Insert: Missing!
Small Time: Missing!
Tidy 5e Sheet: Missing!
Times Up: 10.0.7
Visual Active Effects: Missing!

/////////////// CPR Settings ///////////////
Breaking Version Change: 4
Show Names: true
Priority Queue: true
Movement Listener: true
Template Listener: true
Keep Summon Actors Updated: true
Minions use caster's initiative: true
Effect Auras: true
Active Effect Additions: true
Automatic VAE Descriptions: true
No NPC VAE Descriptions: false
VAE Temporary Item Buttons: false
Condition Fixes: false
LastGM: Xr1u3V90PlQMuvj3
Combat Listener: true
Short / Long Rest Listener: false
Movement Triggers: [object Object]
Use Additional Compendiums: false
Additional Compendiums: midi-srd.Midi SRD Feats, midi-srd.Midi SRD Spells, midi-srd.Midi SRD Items, midi-qol.midiqol-sample-items
Personal Item Compendium: world.ddb-ancient-times-ddb-items
Personal Spell Compendium: world.ddb-ancient-times-ddb-spells
Condition Resistance Mechanic: true
Condition Vulnerability Mechanic: true
On Hit Automation: true
Armor of Agathys Automation: false
Beacon of Hope Automation: false
Darkness Spell Automation: true
Fog Cloud Spell Automation: false
Death Ward Automation: false
Elemental Adept Automation: false
Mirror Image Automation: true
Protection from Evil and Good Automation: true
Sanctuary Automation: false
Ranged Divine Smite: false
Unarmed Strike Divine Smite: false
DMG Cleave Mechanic: false
Shifter Wildhunt Automation: false
Undead Fortitude Automation: true
Exploding Heals: false
Shield Guardian Automation: false
Warding Bond Automation: false
Attack Listener: false

/////////////// Item Macro Settings ///////////////
Character Sheet Hook: false

/////////////// Midi-Qol Settings ///////////////
Roll Automation Support: true
Apply Convenient Effects: None
Roll Seperate Attack Per Target: false
Merge Card: false

/////////////// Warpgate User Permissions ///////////////
Create Tokens: false
Configure Tokens: false
Browse Files: false

**Comment by gioppoluca** [comment]
The last version fixes the issue, now it prompt to attach to token
