### ISSUE TITLE
Missing Chris Premade icon in the character or item sheet title bars

### ISSUE THREAD

**Issue by franckflo** [chrisk123999/chris-premades#79]
There used to be a dedicated icon in the title bar of the character and item sheets to be able to check if there was a corresponding CPR item, and it's not visible anymore.  I tried running Find the Culprit with just CPR and its dependencies, the missing icons were still missing.

Dnd 2.2.1
FVTT 10.291
CPR 0.5.3
All the dependencies are enabled and at the latest version available for FVTT 10. 

I'm attaching my exported settings, zipped.

[foundry-settings-export-2023-06-13-00-37-25-ootd.zip](https://github.com/chrisk123999/chris-premades/files/11728815/foundry-settings-export-2023-06-13-00-37-25-ootd.zip)

**Comment by chrisk123999** [comment]
Find the culprit won't help with this.  Double check that the module is actually active.  If it is type the following into console and share the output file here: `chrisPremades.troubleshoot()`

**Comment by chrisk123999** [comment]
No, there was no response to my last message.

**Comment by franckflo** [comment]
Sorry, 
I had sent you the troubleshooting file through Discord, like you asked back then. 

Sent from Yahoo Mail for iPad


On Tuesday, June 20, 2023, 9:44 a.m., Chris ***@***.***> wrote:




No, there was no response to my last message.

**Comment by franckflo** [comment]
My bad, I had sent you the troubleshooting file via Discord a couple days ago so I thought you didn’t need it here also. I’ll run it again today and you the latest version today. I have fixed a few permissions like config tokens and browse files since. I also tried removing DDB importer before uninstall/reinstall CPR to no avail.

**Comment by chrisk123999** [comment]
Message me on Discord, I'll have to join your server and take a look.

**Comment by franckflo** [comment]
Is now a good a good time or you’d prefer later?

**Comment by chrisk123999** [comment]
Yes
