### ISSUE TITLE
Issue with The Forge due to version numbering

### ISSUE THREAD

**Issue by ravingdragoon** [chrisk123999/chris-premades#8]
The Forge is seeing V0.34 as the newest version because it is missing an additional preceding 0 that all the other releases have, which is stopping it from seeing 0.0.35 as the newest release.

![image](https://user-images.githubusercontent.com/72875320/221896123-339da682-2108-4d40-a60e-c27f40434837.png)

**Comment by chrisk123999** [comment]
I think I've fixed it.  I'll keep this issue open until I can verify it.

**Comment by chrisk123999** [comment]
Issue has been resolved.  The Forge delisted accidental 0.34 version.
