### ISSUE TITLE
Toll the Dead not working

### ISSUE THREAD

**Issue by Aperiusxyz** [chrisk123999/chris-premades#81]
Hi, i'm run Foundry in v10 and all module are up do date, I have been using Tool the Dead and it has always worked but trying it last weekend the damage (the d12) did not appear in case of wounded target, only the d8 appeared in case the target was full hp.

From Console I get this error:

```
Uncaught (in promise) TypeError: undefined. Unable to read properties of undefined (reading '_formula').
[Detected 2 packages: chris-premades, midi-qol].
    a Workflow.tollTheDead (tollTheDead.js:12:45)
    a async Proxy.eval (eval at callMacro (workflow.js:1733:17), <anonymous>:3:8)
    a async Promise.all (index 0)
    a workflow.callMacros async (workflow.js:1596:13)
    a Workflow._next async (workflow.js:507:6)
    a Workflow.next async (workflow.js:248:10)
    a Workflow.next async (workflow.js:248:10)
    a async Workflow.next (workflow.js:248:10)
    a async Workflow.next (workflow.js:248:10)
    a async Workflow.next (workflow.js:248:10)
    a async Workflow.next (workflow.js:248:10)
tollTheDead @ tollTheDead.js:12
wait in tollTheDead (async)		
doItemUse @ itemhandling.js:328
wait in doItemUse (async)		
🎁call_wrapper @ libWrapper-wrapper.js:616
🎁CONFIG.Item.documentClass.prototype.use#0 @ libWrapper-wrapper.js:189
roll @ quick-actions.js:86
(anonymous) @ ui.js:121
```

The line that generates the exception is this:
`let damageFormula = workflow.damageRoll._formula.replace('d8', 'd12');`

Can you fix it?
Thanks

**Comment by chrisk123999** [comment]
I'm unable to reproduce this error.  Does the item have a damage formula set?

**Comment by Aperiusxyz** [comment]
Yes, in the damage formula I have 1d8[necrotic] which is exactly what is written in the compendium.
Looking at the logic of the script it is correct, because if the target is wounded it replaces d8 with d12.

When I hit a full hp target the d8 are thrown correctly, the problem is only with non-full hp targets when there should be d12.

I also report the output of the chrisPremades.troubleshoot() command:
`/////////////// Game Information ///////////////
help.js:49 Foundry: 10.291
help.js:49 System: 2.2.1
help.js:49 Chris's Premades: 0.5.6
help.js:49 
help.js:49 /////////////// Required Modules ///////////////
help.js:49 Automated Animations: 4.2.60
help.js:49 Build A Bonus: 10.5.4
help.js:49 Compendium Folders: 2.5.7
help.js:49 Dynamic Active Effects: 10.0.34.1
help.js:49 DFreds Convenient Effects: 4.2.1
help.js:49 Effect Macro: 10.0.15
help.js:49 Item Macro: 1.8.0
help.js:49 libWrapper: 1.12.12.1
help.js:49 Midi-Qol: 10.0.48.3
help.js:49 Sequencer: 3.0.11
help.js:49 Socketlib: 1.0.13
help.js:49 Template Macro: 10.0.2
help.js:49 Token Attacher: 4.5.12
help.js:49 Warpgate: 1.17.2
help.js:49 
help.js:49 /////////////// Optional Modules ///////////////
help.js:49 About Time: 11.0.0
help.js:49 Advanced Token Effects: Missing!
help.js:49 Custom Character Sheet Sections: Missing!
help.js:49 D&D Beyond Importer: Missing!
help.js:49 Simple Calendar: 2.2.0
help.js:49 FXMaster: Missing!
help.js:49 Jules&Ben's Animated Assets (P): Missing!
help.js:49 Jules&Ben's Animated Assets (F): Missing!
help.js:49 Quick Insert: Missing!
help.js:49 Small Time: 1.16.6
help.js:49 Tidy 5e Sheet: Missing!
help.js:49 Times Up: 11.0.0`

**Comment by MotoMoto1234** [comment]
My 2cents here is that the user is using another roller.

**Comment by Aperiusxyz** [comment]
I solved it myself, I think I was missing some modules that I was sure I had installed.

I'd like to take the opportunity to ask you about something I saw in your faq: I can't find these three entries anywhere, can you tell me where they might be? Because I have them all false

User Permissions for Warpgate:
     - Create New Tokens: checked
     - Configure Token Settings: checked
     - Use File Browser: checked

Thank you

**Comment by MotoMoto1234** [comment]
As the DM, edit user permissions from either core settings or manage users in the settings sidebar.

**Comment by Aperiusxyz** [comment]
> As the DM, edit user permissions from either core settings or manage users in the settings sidebar.

I found them, thank you so much.
I close the issue.
