### ISSUE TITLE
Getting an error on import with Additional Compendiums setting enabled.

### ISSUE THREAD

**Issue by rjbprime** [chrisk123999/chris-premades#84]
Hi @chrisk123999,

I seem to be getting a series of yellow notifications in my FoundryVTT v10 (NOT v11) instance, on the game window, not the dev tools console, when importing anything from DNDBeyond, into either compendiums OR Actors (those are what I have noticed, possibly other item types are affected, haven't checked them all).

Is this an issue with still using v10? And is there an option to both use the additional compendiums and disable that notification, or is it a case of it's a v11 feature that shouldn't be in use for v10?

Kind regards.

**Comment by chrisk123999** [comment]
Screenshot the error if you can.  If you're importing with the D&D Beyond importer, my module is very unlikely to cause errors with it.

**Comment by chrisk123999** [comment]
You may wish to run that by MrPrimate.  There's not much I can do about that from my side.
