### ISSUE TITLE
The module does not load for me on V11

### ISSUE THREAD

**Issue by gris-x** [chrisk123999/chris-premades#85]
It says it is missing a dependency but I have activated all modules listed in the page indicating what modules are required.
Using forge to host my games...

**Comment by redjama** [comment]
> It says it is missing a dependency but I have activated all modules listed in the page indicating what modules are required. Using forge to host my games...

Look and see if "Item Macro" is showing in your list of installed modules.  Seems to be the issue at least on my game

**Comment by chrisk123999** [comment]
I just removed Item Macro as a hard dependency.  Let me know if this fixes the issue.
