### ISSUE TITLE
Maneuvers DC not scaling

### ISSUE THREAD

**Issue by Dairid** [chrisk123999/chris-premades#9]
So I tried a few of the combat maneuvers on a DDB imported Battlemaster, they work very well, automate well and are intuitive.  The DC though is set at 10 and seems that it doesn't scale with the battlemaster scaling DC for saves (should be 8+prof+STR/DEX (whichever is larger would probably be how you'd code it).

**Comment by chrisk123999** [comment]
Double check what ability the feature is set to be using.  By default it's using your spellcasting modifier, but should be changed to either dexterity or strength.
![Capture](https://user-images.githubusercontent.com/2249355/224143497-619e155a-cbc1-45d6-b572-98bf0519d954.PNG)

**Comment by Dairid** [comment]
yeah I had to go to my spellbook in my character sheet and select STR as my spellcasting ability, that fixed it then.  I guess if you  were multiclassed then you'd need to likely do it manually for each maneuver.
