### ISSUE TITLE
Bug: Animated token images for Spiritual Weapon are not working

### ISSUE THREAD

**Issue by Sisimshow** [chrisk123999/chris-premades#92]
It seems when you summon a Spiritual Weapon using the new premade, if you select Dark, Scythe, and any color, the image chosen for the token does not apply correctly and only shows the default white hooded stranger token. Looking at the token's appearance settings, it seems that the end of the image's file name is incorrectly set as 200x200.webp where it should be 300x300.webp for the scythe animations. 

![Screenshot 2023-07-07 201910](https://github.com/chrisk123999/chris-premades/assets/126213271/32e5f398-5d3d-4298-9181-16220c634650)

**Comment by Autumn225** [comment]
That should be fixed in the next update, where it'll be changed to getting the files out of the sequencer database. Beginning of next week most likely. If you want to use a specific scythe for now you can put it in the configuration for the item.
