### ISSUE TITLE
Swarm Attacks Don't appear to work

### ISSUE THREAD

**Issue by rdefendi** [chrisk123999/chris-premades#93]
The macro that reduces the amount of damage a swarm does when a swarm is below half HP doesn't seem to be working properly in. I can't seem to spot what's going wrong when I try to use it. I can usually spot an obvious error in the console, but not this time. It's set to trigger after damage and I've tried some other options such as before damage, but none seem to change the behavior.

**Comment by chrisk123999** [comment]
It very much should be running after damage roll.  Could you go to the settings of this module, and hit the troubleshooter button (near the bottom) and drop the file it outputs here?

**Comment by rdefendi** [comment]
[CPR-Troubleshoot.txt](https://github.com/chrisk123999/chris-premades/files/12021847/CPR-Troubleshoot.txt)
Here you go. Sorry it took a minute. I posted the issue at lunch then saw your reply right after I went back to work.

**Comment by chrisk123999** [comment]
I don't see anything obvious wrong with the setting that would affect this.  What swarm monster is specifically having this issue?

**Comment by rdefendi** [comment]
I've tried with a couple, both with attacks I pull fresh out of the DDB Monsters version of the monster and with attacks I had edited to have a versatile version of the attack after I found the issue (because I wanted the option of manually holding down a key to force it to do half damage to manually do half damage.) with those I just copied your macro line from one of the pristine attacks. Both didn't work. With the fresh creature, was a swarm of insects (wasps). I'd renamed the monster to just "Swarm of Wasps" but I don't think that should matter. I've also tried with Swarm of Poisonous Snakes and Swarm of Rats. Those two I'd probably just copied the macro line in. I also tried with a custom monster Swarm of Zombie, where I copied the swarm of wasps attack and just edited the damage line.

**Comment by chrisk123999** [comment]
I'll double check this when I get a chance.

**Comment by rdefendi** [comment]
Is this working on yours? I can do a find the culprit check real quick (well not REAL quick, they take a bit and aren't super reliable). I didn't think of it because I'm hitting so many bugs right now that v11 released.

**Comment by chrisk123999** [comment]
Was working last I checked.  Do you have a target selected when you're attacking?

**Comment by rdefendi** [comment]
Yeah, I'm attacking a generic ghoul. He has perished many times.

**Comment by rdefendi** [comment]
Okay, I just tested. I DO have the same problem with a swarm of bats attacking a ghoul and just midi-qol, premades, and the dependencies loaded. That should be:
midi
socketlib
libwrapper

chris's premades
dae
dfreds
warp gate
effect macro
template macro
sequencer
token attacher
build a bonus
automated animations

**Comment by chrisk123999** [comment]
This should be fixed in the latest release.
