### ISSUE TITLE
CPR - Undead Spirit missing configure images

### ISSUE THREAD

**Issue by KammaKhazi** [chrisk123999/chris-premades#95]
hi, I noticed that my Summon Undead had stopped working (no token/avatar art). So I updated the spell with a fresh copy from the compendium and enabled "Keep Summon Actors Updated". I notice the new CPR - Undead Spirit no longer has the "configure images" feature. I copied my old version across and ran the macro but my summons are still no token/avatar art.
kind regards

**Comment by chrisk123999** [comment]
On the spell in the inventory press the medkit button then hit configure.

**Comment by KammaKhazi** [comment]
Dang it sorry. Worked a charm many thanks.
